// build.mjs — zero-npm build for the hex lane.
// 1. copies the estate quantizer sources VERBATIM (byte-exact, never edited)
//    from the PixelRefiner mirror into vendor-ref/ so the demo compiles against
//    the REAL quantizer, unchanged (provenance recorded beside them);
// 2. compiles hex/*.ts + vendor-ref with the mirror's own local tsc binary
//    (on-disk toolchain — nothing installed, no network).
// The five hex modules are the source of truth; dist/ is generated output.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync, existsSync, rmSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const HEX = join(HERE, "..");
const MIRROR = "C:/Users/travi/raids/PixelRefiner";
const TSC = join(MIRROR, "node_modules/typescript/bin/tsc");

// ── 1. verbatim vendor-ref copy ──────────────────────────────────────────────
const COPY = [
	["src/core/quantizer.ts", "vendor-ref/core/quantizer.ts"],
	["src/core/colorUtils.ts", "vendor-ref/core/colorUtils.ts"],
	["src/shared/types.ts", "vendor-ref/shared/types.ts"],
];
for (const [, dest] of COPY) mkdirSync(join(HEX, dirname(dest)), { recursive: true });
for (const [src, dest] of COPY) copyFileSync(join(MIRROR, src), join(HEX, dest));
writeFileSync(
	join(HEX, "vendor-ref/PROVENANCE.txt"),
	[
		"The three files in vendor-ref/ are BYTE-EXACT copies generated by tools/build.mjs",
		"from the PixelRefiner mirror at " + MIRROR + " (MIT, verified at commit bd5c1c7).",
		"They are regenerated on every build — never hand-edited, never forked.",
		"The hex modules hand their results to this quantizer UNCHANGED: it is",
		"lattice-agnostic. FENCE: do not edit anything under vendor-ref/ by hand.",
	].join("\n") + "\n",
);

// ── 2. compile ───────────────────────────────────────────────────────────────
if (!existsSync(TSC)) {
	console.error("FAIL build: mirror tsc not found at", TSC);
	process.exit(1);
}
rmSync(join(HEX, "dist"), { recursive: true, force: true });
execFileSync(process.execPath, [TSC, "-p", join(HEX, "tsconfig.json")], { stdio: "inherit" });

// The verbatim vendor sources import bundler-style (extensionless); their
// emitted JS gets explicit .js extensions here so dist/ runs in browser+node.
// Generated output only — vendor-ref/ itself stays byte-exact.
for (const [, dest] of COPY) {
	const out = join(HEX, "dist", dest.replace(/\.ts$/, ".js"));
	let src = readFileSync(out, "utf8");
	const fixed = src.replace(/(from\s+["']\.\.?\/[^"'.]+)["']/g, '$1.js"');
	if (fixed !== src) writeFileSync(out, fixed);
}
console.log("OK build: dist/ compiled from hex/*.ts + verbatim vendor-ref/");
