// gen_verifier.js — emits verify_min.cpp: a minimal Groth16 SHAPE verifier for jungle4.
//
// WHAT THIS VERIFIES (stated exactly, no stronger): the full Groth16 pairing
// equation e(A,B)·e(-α,β)·e(-vk_x,γ)·e(-C,δ) = 1 under a TOY instance whose
// keys are generator points and whose "proof" is constructed algebraically
// (A=g1, B=g2, C=-g1 ⇒ product = e^(1-1+1-1) = 1). The pairing COUNT is the
// production count (4 pairs, one alt_bn128_pair call) — the billed CPU is
// what a real-circuit Groth16 verification costs. A meaningful circuit rides
// the same action after the M2 fork is ruled.
//
// Constants source: py_ecc bn128_curve.py (G1=(1,2) line 36; G2 line 38);
// EVM/EIP-197 pair encoding: G1 = x‖y (32B BE each), G2 = x_im‖x_re‖y_im‖y_re.
const fs = require('fs');
const read = p => { try { return fs.readFileSync(p, 'utf8'); } catch { return null; } };
const src = read('C:/Users/travi/zkbench/pyecc_curve.js') || read('/mnt/c/Users/travi/zkbench/pyecc_curve.py');

const P = 21888242871839275222246405745257275088696311157297823662689037894645226208583n; // PUBLIC-CONSTANT BN254 field prime (py_ecc/EIP-197)
const w32 = v => v.toString(16).padStart(64, '0');
const g1hex = (x, y) => w32(x) + w32(y);
const g2hex = (x0, x1, y0, y1) => w32(x1) + w32(x0) + w32(y1) + w32(y0); // im word first (EIP-197)

const G1X = 1n, G1Y = 2n;
const G2 = [ // [x0, x1, y0, y1] from py_ecc bn128_curve.py:38-47
  10857046999023057135944570762232829481370756359578518086990519993285655852781n, // PUBLIC-CONSTANT BN254 G2 x_c0
  11559732032986387107991004021392285783925812861821192530917403151452391805634n, // PUBLIC-CONSTANT BN254 G2 x_c1
  8495653923123431417604973247489272438418190587263600148770280649306958101930n, // PUBLIC-CONSTANT BN254 G2 y_c0
  4082367875863433681332203403145435568316851327593401208105741076214120093531n, // PUBLIC-CONSTANT BN254 G2 y_c1
];

// key & proof (toy instance): alpha=g1 beta=gamma=delta=g2 IC0=g1; A=g1 B=g2 C=-g1
const g1b = g1hex(G1X, G1Y);
const g2b = g2hex(G2[0], G2[1], G2[2], G2[3]);
const negG1 = g1hex(G1X, P - G1Y);

const pair = (a, b) => a + b; // 64B + 128B
// e(-A,B) · e(α,β) · e(IC0,γ) · e(C,δ) = 1
const GOOD = pair(negG1, g2b) + pair(g1b, g2b) + pair(g1b, g2b) + pair(negG1, g2b);
// negative control: C flipped to +g1 → product = e(g1,g2) ≠ 1 → alt_bn128_pair returns 1
const BAD  = pair(negG1, g2b) + pair(g1b, g2b) + pair(g1b, g2b) + pair(g1b, g2b);

const cpp = `// verify_min.cpp — GENERATED by gen_verifier.js. Minimal Groth16-shape verifier.
// The equation, the encoding, the toy-instance caveat: see gen_verifier.js and
// docs/specs/SPEC-PRIVACY-1.md. One alt_bn128_pair call over 4 pairs = the
// production Groth16 verification cost. Sound by construction: the action
// accepts only if the chain's own pairing check returns true.
#include <eosio/eosio.hpp>
#include <eosio/crypto_ext.hpp>
using namespace eosio;

class [[eosio::contract("verifymin")]] verifymin : public contract {
public:
   using contract::contract;

   static constexpr uint32_t NBYTES = 768; // 4 pairs x 192 bytes

   [[eosio::action]] void verify() {
      // e(-A,B)·e(α,β)·e(vk_x,γ)·e(C,δ) under the toy key; expected: 0 (true)
      static const unsigned char pairs[768] = { ${GOOD.match(/../g).map(h => '0x' + h).join(',')} };
      int32_t r = alt_bn128_pair( (const char*)pairs, sizeof(pairs) );
      eosio::check( r == 0, "pairing check FALSE — proof rejected" );
   }

   [[eosio::action]] void verifybad() {
      // negative control: C flipped to +g1 — product != 1, must REJECT
      static const unsigned char pairs[768] = { ${BAD.match(/../g).map(h => '0x' + h).join(',')} };
      int32_t r = alt_bn128_pair( (const char*)pairs, sizeof(pairs) );
      eosio::check( r == 1, "negative control did not reject" );
   }
};
`;
const out = process.env.WSL_DISTRO_NAME ? '/mnt/c/Users/travi/zkbench/verify_min.cpp' : 'C:/Users/travi/zkbench/verify_min.cpp';
fs.writeFileSync(out, cpp);
console.log('verify_min.cpp written · good pairs 768B · bad pairs 768B');
