// gen_poseidon_cpp.js — circomlib's Poseidon (t=3, nInputs=2) → poseidon2.hpp
// (C++ over field256, Montgomery-domain constants) + tree_zeros.hpp (the
// depth-20 zero chain for the ON-CHAIN incremental tree) + cross-vectors
// from circomlibjs for the native gate.
//
// Single source of truth: the constants are PARSED from circomlib's own
// poseidon_constants.circom (t==3 blocks) — never retyped by hand. The
// structure mirrors poseidon.circom's PoseidonEx(nInputs=2, 1): initial
// state (0, in0, in1); 3 full rounds (σ+Ark+Mix M); a middle round with the
// P matrix; 57 partial rounds (σ on state[0] with the Ark constant folded,
// then the sparse S-matrix MixS); 3 more full rounds; final σ + MixLast
// (M row 0). Round constant layout: C[0..2] ark0; C[3..11] first half;
// C[12..14] middle; C[15..71] partial (folded); C[72..80] second half.
const fs = require('fs');
const path = require('path');

const CIRCOM_LIB = process.env.CIRCOMLIB_DIR || '/home/travi/plonkport/node_modules/circomlib';
const src = fs.readFileSync(path.join(CIRCOM_LIB, 'circuits/poseidon_constants.circom'), 'utf8');

function extractBlock(fnName) {
   // take the hex tokens of the `else if (t==3)` branch of POSEIDON_<fnName>
   const fnStart = src.indexOf(`function POSEIDON_${fnName}(t) {`);
   if (fnStart < 0) throw new Error('no ' + fnName);
   const rest = src.slice(fnStart);
   const b3 = rest.indexOf('else if (t==3)');
   if (b3 < 0) throw new Error('no t==3 branch in ' + fnName);
   const after = rest.slice(b3);
   const end = after.indexOf('} else', 10);
   const block = end < 0 ? after : after.slice(0, end);
   return [...block.matchAll(/0x[0-9a-fA-F]+/g)].map(m => m[0]);
}

const C = extractBlock('C');     // 81
const M = extractBlock('M');     // 9
const P = extractBlock('P');     // 9
const S = extractBlock('S');     // 285
if (C.length !== 81) throw new Error('C length ' + C.length);
if (M.length !== 9) throw new Error('M length ' + M.length);
if (P.length !== 9) throw new Error('P length ' + M.length);
if (S.length !== 285) throw new Error('S length ' + S.length);

const decBytes = (hex, per = 16) => {
   const v = BigInt(hex);
   const b = [];
   for (let i = 31; i >= 0; --i) b.push(Number((v >> BigInt(8 * i)) & 255n));
   const parts = [];
   for (let i = 0; i < b.length; i += per) parts.push('   ' + b.slice(i, i + per).join(',') + ',');
   return '\n' + parts.join('\n');
};
const arr = (name, hexes) =>
   `static constexpr unsigned char ${name}[${hexes.length}][32] = {` +
   hexes.map(h => decBytes(h)).join('\n') + '\n};';

// ── the zero chain (circomlibjs Poseidon — same parameters) ──
(async () => {
   const { buildPoseidonOpt } = require(path.join(CIRCOM_LIB, '..', 'circomlibjs'));
   const poseidon = await buildPoseidonOpt();
   const H = (a, b) => poseidon.F.toString(poseidon([a, b]));
   const zeros = ['0'];
   for (let i = 1; i <= 20; i++) zeros.push(H(zeros[i - 1], zeros[i - 1]));

   const w32 = v => BigInt(v).toString(16).padStart(64, '0');
   const vectors = [];
   const rnd = () => BigInt('0x' + require('crypto').randomBytes(30).toString('hex'));
   vectors.push(['0', '0', H(0, 0)]);
   vectors.push(['1', '0', H(1, 0)]);
   vectors.push(['0', '1', H(0, 1)]);
   vectors.push(['18446744073709551615', '1', H('18446744073709551615', '1')]);   // 2^64−1 edge
   for (let i = 0; i < 60; i++) { const a = rnd(), b = rnd(); vectors.push([a.toString(), b.toString(), H(a.toString(), b.toString())]); }
   // tree-shaped vectors: consecutive zero-chain hashes
   vectors.push([zeros[0], zeros[0], zeros[1]]);
   vectors.push([zeros[19], zeros[19], zeros[20]]);

   // M8: emit the round constants PRE-CONVERTED to Montgomery form (v·R mod q)
   // — the per-call conversion loop (384 mont-muls + parses per insert) is gone.
   const QR = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;  // PUBLIC-CONSTANT BN254 scalar field (template l.28)
   const R = (1n << 256n) % QR;
   const toMont = hex => '0x' + ((BigInt(hex) * R) % QR).toString(16);

   const hpp = [];
   hpp.push('// poseidon2.hpp — GENERATED by gen_poseidon_cpp.js from circomlib\'s');
   hpp.push('// poseidon_constants.circom (t==3). DO NOT EDIT BY HAND. Round structure');
   hpp.push('// mirrors poseidon.circom PoseidonEx(2,1) verbatim (see the generator');
   hpp.push('// header for the round/constant layout). Constants are stored');
   hpp.push('// PRE-CONVERTED to Montgomery form (v·R mod q, M8) — poseidon2_ctx_init');
   hpp.push('// does NO constant work; the t=3 instance is bound to the BN254 scalar');
   hpp.push('// field (the mont conversion is modulus-specific by construction).');
   hpp.push('// COMPATIBILITY GATE: test_poseidon.cpp checks this implementation');
   hpp.push('// against circomlibjs on ' + vectors.length + ' vectors BEFORE any chain use.');
   hpp.push('#pragma once');
   hpp.push('#include "field256.hpp"');
   hpp.push('');
   const arr256 = (name, hexes) => {
      const rows = hexes.map(h => {
         const v = BigInt(h);
         const limbs = [0n, 0n, 0n, 0n];
         for (let k = 0; k < 4; k++) limbs[k] = (v >> BigInt(64 * k)) & 0xffffffffffffffffn;
         return '   {' + limbs.map(x => x.toString() + 'ull').join(',') + '},';
      });
      return `static const uint64_t ${name}[${hexes.length}][4] = {\n` + rows.join('\n') + '\n};';
   };
   hpp.push(arr256('POSE_C', C.map(toMont)));
   hpp.push(arr256('POSE_M', M.map(toMont)));
   hpp.push(arr256('POSE_P', P.map(toMont)));
   hpp.push(arr256('POSE_S', S.map(toMont)));
   hpp.push(`
// ── the t=3 instance. M8: the ctx is the BARE field context — every round
// constant above is already Montgomery-form; init does ZERO constant work. ──
struct poseidon2_ctx {
   fctx fq;
};

static void poseidon2_ctx_init( poseidon2_ctx* pc, const unsigned char q_be[32] ) {
   u256 q; f256_from_be( q, q_be );
   fctx_init( &pc->fq, q );   // must be the BN254 scalar field (the constants are bound to it)
}

// σ(x) = x⁵ entirely in Montgomery form: MM(x,x)=x²R, MM(x²,x²)=x⁴R, MM(x⁴,x)=x⁵R
static inline void p2_sigma( const fctx* f, const u256 x, u256 out ) {
   u256 x2, x4;
   mont_mul( f, x, x, x2 );
   mont_mul( f, x2, x2, x4 );
   mont_mul( f, x4, x, out );
}
// st[i] = Σ_j M[j][i]·s[j]  (constants Montgomery-form ⇒ result stays in form)
static inline void p2_matvec( const fctx* f, const u256 mrow[9], const u256 s[3], u256 st[3] ) {
   u256 t0, t1, t2;
   mont_mul( f, s[0], mrow[0], t0 ); mont_mul( f, s[1], mrow[3], t1 ); mont_mul( f, s[2], mrow[6], t2 );
   f_add( f, t0, t1, t0 ); f_add( f, t0, t2, st[0] );
   mont_mul( f, s[0], mrow[1], t0 ); mont_mul( f, s[1], mrow[4], t1 ); mont_mul( f, s[2], mrow[7], t2 );
   f_add( f, t0, t1, t0 ); f_add( f, t0, t2, st[1] );
   mont_mul( f, s[0], mrow[2], t0 ); mont_mul( f, s[1], mrow[5], t1 ); mont_mul( f, s[2], mrow[8], t2 );
   f_add( f, t0, t1, t0 ); f_add( f, t0, t2, st[2] );
}

// out = H(a, b) — circomlib Poseidon(2)
static void poseidon2( const poseidon2_ctx* pc, const u256 a, const u256 b, u256 out ) {
   const fctx* f = &pc->fq;
   u256 st[3], s[3], t1, t2, t3;
   // initial state (0, a, b), ark[0]
   f256_zero( st[0] );
   mont_mul( f, a, f->r2, st[1] ); mont_mul( f, b, f->r2, st[2] );
   f_add( f, st[0], POSE_C[0], st[0] ); f_add( f, st[1], POSE_C[1], st[1] ); f_add( f, st[2], POSE_C[2], st[2] );
   // first half: 3 full rounds (σ + ark C[3..11] + Mix M)
   for ( int r = 0; r < 3; ++r ) {
      for ( int j = 0; j < 3; ++j ) { p2_sigma( f, st[j], s[j] ); f_add( f, s[j], POSE_C[3*(r+1)+j], s[j] ); }
      p2_matvec( f, POSE_M, s, st );
   }
   // middle round: σ + ark C[12..14] + Mix P
   for ( int j = 0; j < 3; ++j ) { p2_sigma( f, st[j], s[j] ); f_add( f, s[j], POSE_C[12+j], s[j] ); }
   p2_matvec( f, POSE_P, s, st );
   // 57 partial rounds: σ(state[0]) + folded C[15+r], sparse MixS with S
   for ( int r = 0; r < 57; ++r ) {
      p2_sigma( f, st[0], t1 );
      f_add( f, t1, POSE_C[15 + r], t1 );
      // out0 = Σ S[5r+i]·in_i ; out_i = in_i + in_0·S[5r+2+i]
      mont_mul( f, t1, POSE_S[5*r+0], t2 );
      u256 t4; mont_mul( f, st[1], POSE_S[5*r+1], t3 ); f_add( f, t2, t3, t2 );
      u256 t5; mont_mul( f, st[2], POSE_S[5*r+2], t4 ); f_add( f, t2, t4, t5 );   // new0
      u256 n1, n2;
      mont_mul( f, t1, POSE_S[5*r+3], t2 ); f_add( f, st[1], t2, n1 );
      mont_mul( f, t1, POSE_S[5*r+4], t2 ); f_add( f, st[2], t2, n2 );
      f256_copy( st[0], t5 ); f256_copy( st[1], n1 ); f256_copy( st[2], n2 );
   }
   // second half: 3 full rounds (σ + ark C[72..80] + Mix M)
   for ( int r = 0; r < 3; ++r ) {
      for ( int j = 0; j < 3; ++j ) { p2_sigma( f, st[j], s[j] ); f_add( f, s[j], POSE_C[72+3*r+j], s[j] ); }
      p2_matvec( f, POSE_M, s, st );
   }
   // final: σ on all + MixLast (M row 0)
   u256 acc, one;
   f256_set_u64( one, 1 );
   f256_zero( acc );
   for ( int j = 0; j < 3; ++j ) {
      p2_sigma( f, st[j], s[j] );
      u256 t; mont_mul( f, s[j], POSE_M[3*j], t );   // M[j][0] — flat layout m[j*3+0]
      f_add( f, acc, t, acc );
   }
   mont_mul( f, acc, one, out );                  // leave Montgomery form
}
`);
   fs.writeFileSync(process.argv[2] || 'poseidon2.hpp', hpp.join('\n'));

   // tree_zeros.hpp — the zero chain (zeros[0]=0 … zeros[20]=empty root)
   const zhex = zeros.map(z => w32(z));
   const zfile = ['// tree_zeros.hpp — GENERATED by gen_poseidon_cpp.js (circomlibjs zero',
      '// chain, depth 20: zeros[0]=0, zeros[l]=Poseidon(zeros[l-1], zeros[l-1])).',
      '// ZERO_[i] is the empty-sibling hash at level i; ZERO_[20] = the empty-tree',
      '// root (the law row\'s initial root). tree.js agrees by construction.',
      '#pragma once',
      arr('ZERO_', zhex.map(h => '0x' + h)),
      ''].join('\n');
   fs.writeFileSync(process.argv[3] || 'tree_zeros.hpp', zfile);

   fs.writeFileSync(process.argv[4] || 'poseidon_vectors.txt',
      vectors.map(([a, b, h]) => `P2 ${w32(a)} ${w32(b)} ${w32(h)}`).join('\n') + '\n');
   console.log('poseidon2.hpp + tree_zeros.hpp + ' + vectors.length + ' vectors written');
   console.log('empty root =', zeros[20]);
})();
