// gen_plonk.js — emits plonk_verify_min.cpp: a PLONK-SHAPE verifier for the rehearsal chain.
//
// WHAT THIS MEASURES (stated exactly): the billed CPU of a PLONK verification
// with the PRODUCTION OPERATION COUNT — 6 keccak256 transcript calls, 2 mod_exp
// field inversions, 12 G1 scalar multiplications, 12 G1 additions, and one
// pairing product check over 4 pairs — mirroring the shape of snarkjs's PLONK
// Solidity verifier (precompile usage: alt_bn128 ops + keccak + modexp).
// The key/proof points are generator-derived toy values chosen so the final
// pairing product equals 1 (the same labeled-toy discipline as M1's Groth16
// receipt). A circuit-backed proof (snarkjs plonk) rides the SAME op count;
// that integration is M3 work under the ruled fork.
//
// Constants source: py_ecc bn128_curve.py:36-47 (G1=(1,2), G2 generator) — PUBLIC-CONSTANT.
const fs = require('fs');
const P = 21888242871839275222246405745257275088696311157297823662689037894645226208583n; // PUBLIC-CONSTANT BN254 field prime (py_ecc/EIP-197)
const w32 = v => v.toString(16).padStart(64, '0');
const g1hex = (x, y) => w32(x) + w32(y);
const g2hex = (x0, x1, y0, y1) => w32(x1) + w32(x0) + w32(y1) + w32(y0);
const G1X = 1n, G1Y = 2n;
const G2 = [ // PUBLIC-CONSTANT BN254 G2 generator (py_ecc bn128_curve.py:38)
  10857046999023057135944570762232829481370756359578518086990519993285655852781n, // PUBLIC-CONSTANT BN254 G2 x_c0
  11559732032986387107991004021392285783925812861821192530917403151452391805634n, // PUBLIC-CONSTANT BN254 G2 x_c1
  8495653923123431417604973247489272438418190587263600148770280649306958101930n, // PUBLIC-CONSTANT BN254 G2 y_c0
  4082367875863433681332203403145435568316851327593401208105741076214120093531n, // PUBLIC-CONSTANT BN254 G2 y_c1
];
const g1b = g1hex(G1X, G1Y);
const g2b = g2hex(G2[0], G2[1], G2[2], G2[3]);
const negG1 = g1hex(G1X, P - G1Y);
const pair = (a, b) => a + b;

// 4-pair product = 1 (two positives, two negatives — same algebra as M1)
const GOOD_PAIRS = pair(negG1, g2b) + pair(g1b, g2b) + pair(g1b, g2b) + pair(negG1, g2b);
const BAD_PAIRS  = pair(negG1, g2b) + pair(g1b, g2b) + pair(g1b, g2b) + pair(g1b, g2b);

const cpp = `// plonk_verify_min.cpp — GENERATED by gen_plonk.js. PLONK-shape verifier, M2.5.
// Toy instance labeled exactly; op count = production. See gen_plonk.js header.
#include <eosio/eosio.hpp>
#include <eosio/crypto_ext.hpp>
using namespace eosio;

class [[eosio::contract("plonkbench")]] plonkbench : public contract {
public:
   using contract::contract;

   // one scalar-mul chain: r = r*s + p (marshal/unmarshal via the intrinsic),
   // standing in for the verifier's G1 linear combinations.
   static constexpr int MULS = 12;
   static constexpr int ADDS = 12;
   static constexpr int KECCAKS = 6;
   static constexpr int MODEXPS = 2;

   [[eosio::action]] void verify() {
      static const unsigned char g1pt[64] = { ${g1b.match(/../g).map(h => '0x' + h).join(',')} };
      static const unsigned char pairs[768] = { ${GOOD_PAIRS.match(/../g).map(h => '0x' + h).join(',')} };
      unsigned char acc[64]; unsigned char out[64]; unsigned char hbuf[64]; unsigned char g2pt[64];
      for ( int b2 = 0; b2 < 64; ++b2 ) g2pt[b2] = g1pt[b2];
      eosio::check( alt_bn128_add((const char*)g1pt,64,(const char*)g2pt,64,(char*)acc,64) == 0, "add init" );
      // 12 G1 scalar-mul round trips (mul intrinsic marshals in/out)
      for ( int i = 0; i < MULS; ++i )
         eosio::check( alt_bn128_mul((const char*)acc,64,(const char*)g1pt,32,(char*)out,64) == 0, "mul" ),
         eosio::check( alt_bn128_add((const char*)out,64,(const char*)g2pt,64,(char*)acc,64) == 0, "lcomb" );
      // 6 keccak transcript steps
      for ( int i = 0; i < KECCAKS; ++i ) {
         auto d = keccak( (const char*)hbuf, 32 );
         for (int b = 0; b < 32; ++b) hbuf[b] = d.data()[b];
      }
      // 2 field inversions via mod_exp (a^(p-2) = a^-1)
      unsigned char pm2[32] = { ${w32(P - 2n).match(/../g).map(h => '0x' + h).join(',')} };
      unsigned char inv[32];
      unsigned char modb[32];
      for ( int b2 = 0; b2 < 32; ++b2 ) modb[b2] = pm2[b2];
      for ( int i = 0; i < MODEXPS; ++i )
         eosio::check( mod_exp((const char*)g1pt,32,(const char*)pm2,32,(const char*)modb,32,(char*)inv,32) == 0, "modexp" );
      // the pairing product — production cost center
      int32_t r = alt_bn128_pair( (const char*)pairs, sizeof(pairs) );
      eosio::check( r == 0, "pairing check FALSE — proof rejected" );
   }

   [[eosio::action]] void verifybad() {
      static const unsigned char pairs[768] = { ${BAD_PAIRS.match(/../g).map(h => '0x' + h).join(',')} };
      int32_t r = alt_bn128_pair( (const char*)pairs, sizeof(pairs) );
      eosio::check( r == 1, "negative control did not reject" );
   }
};
`;
const out = process.env.WSL_DISTRO_NAME ? '/mnt/c/Users/travi/zkbench/plonk_verify_min.cpp' : 'C:/Users/travi/zkbench/plonk_verify_min.cpp';
fs.writeFileSync(out, cpp);
console.log('plonk_verify_min.cpp written · 12 mul + 12 add + 6 keccak + 2 modexp + 4-pair product');
