#!/usr/bin/env python3
"""seatscan — list seat-agent pubkeys from the buzz app's local state into
docs/dispatches/SEAT-PUBKEYS.md. Public keys only; never reads or copies secrets.

Sources scanned (read-only): ~/.buzz/**, %APPDATA%/buzz/**, %LOCALAPPDATA%/buzz/**.
Any JSON/TOML/text file is searched for `npub1...` strings and for objects carrying
an agent/seat name next to a `pubkey`/`npub`/`public_key` field. Files whose name
contains `nsec`, `secret`, `key.pem` or whose content matches `nsec1` are SKIPPED
entirely, so no secret is ever loaded into memory. Seats with nothing found → MISSING.
"""
import os, re, json, pathlib, datetime, sys

SEATS = ["z2.1", "z3.1", "z3.2", "z3.3", "goose", "code"]
NPUB = re.compile(r"\bnpub1[02-9ac-hj-np-z]{58}\b")
HEX = re.compile(r"\b[0-9a-f]{64}\b")
SKIP_NAME = re.compile(r"nsec|secret|\.pem$|\.key$", re.I)

def roots():
    h = pathlib.Path.home()
    for p in [h / ".buzz", pathlib.Path(os.environ.get("APPDATA", "")) / "buzz", pathlib.Path(os.environ.get("LOCALAPPDATA", "")) / "buzz"]:
        if p and p.exists():
            yield p

found = {}   # seat -> (pubkey, source)
for root in roots():
    for f in root.rglob("*"):
        if not f.is_file() or SKIP_NAME.search(f.name) or f.stat().st_size > 4_000_000:
            continue
        try:
            txt = f.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if "nsec1" in txt:
            continue  # secret-bearing file: skip whole file
        try:
            data = json.loads(txt)
        except Exception:
            data = None
        def walk(o, name=None):
            if isinstance(o, dict):
                n = o.get("name") or o.get("agent") or o.get("seat") or o.get("label") or name
                pk = o.get("npub") or o.get("pubkey") or o.get("public_key") or o.get("publicKey")
                if n and isinstance(pk, str) and (NPUB.fullmatch(pk) or HEX.fullmatch(pk)):
                    key = str(n).lower()
                    for s in SEATS:
                        if s in key and s not in found:
                            found[s] = (pk, str(f.relative_to(root.parent)))
                for v in o.values():
                    walk(v, n)
            elif isinstance(o, list):
                for v in o:
                    walk(v, name)
        if data is not None:
            walk(data)
        # loose text fallback: "<seat> ... npub1..." on one line
        for line in txt.splitlines():
            m = NPUB.search(line)
            if m:
                low = line.lower()
                for s in SEATS:
                    if s in low and s not in found:
                        found[s] = (m.group(0), str(f.relative_to(root.parent)))

out = pathlib.Path(__file__).resolve().parents[2] / "docs" / "dispatches" / "SEAT-PUBKEYS.md"
stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%MZ")
rows = ["# SEAT PUBKEYS — buzz seat agents (public keys only)", "",
        f"Generated by tools/bdispatch/seatscan.py on {stamp}. Secrets never read. MISSING = no pubkey found in the buzz app's local state; the watcher holds that seat's mail until a row is filled.", "",
        "| seat | pubkey (npub or hex) | source |", "|---|---|---|"]
for s in SEATS:
    pk, src = found.get(s, ("MISSING", "—"))
    rows.append(f"| {s} | {pk} | {src} |")
out.write_text("\n".join(rows) + "\n", encoding="utf-8")
print("\n".join(rows))
missing = [s for s in SEATS if s not in found]
if missing:
    print("seatscan: MISSING", ", ".join(missing), file=sys.stderr)
