// GENERATED FROM surfaces/blight/bcomb.js — DO NOT EDIT BY HAND.
// Regenerate with the gen_rust.cjs oracle script. The JS is canon: it sorts the
// axial grid by ring, then by atan2(r, q), an ordering that is awkward to
// reproduce exactly in a no_std const context and pointless to risk drifting.
// Emitting the table removes that whole class of bug.

/// One hexagon of the comb.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Cell {
    /// Axial q coordinate.
    pub q: i8,
    /// Axial r coordinate.
    pub r: i8,
    /// Ring 0 (core) through 6 (rim).
    pub ring: u8,
    /// Index into the 84 data bits, or -1 for a cell that carries none.
    pub data_index: i16,
}

/// All 127 cells, in the canonical order the codec assigns bits.
pub static CELLS: [Cell; 127] = [
    Cell {
        q: 0,
        r: 0,
        ring: 0,
        data_index: -1,
    },
    Cell {
        q: 0,
        r: -1,
        ring: 1,
        data_index: -1,
    },
    Cell {
        q: 1,
        r: -1,
        ring: 1,
        data_index: -1,
    },
    Cell {
        q: 1,
        r: 0,
        ring: 1,
        data_index: -1,
    },
    Cell {
        q: 0,
        r: 1,
        ring: 1,
        data_index: -1,
    },
    Cell {
        q: -1,
        r: 1,
        ring: 1,
        data_index: -1,
    },
    Cell {
        q: -1,
        r: 0,
        ring: 1,
        data_index: -1,
    },
    Cell {
        q: -1,
        r: -1,
        ring: 2,
        data_index: 0,
    },
    Cell {
        q: 0,
        r: -2,
        ring: 2,
        data_index: 1,
    },
    Cell {
        q: 1,
        r: -2,
        ring: 2,
        data_index: 2,
    },
    Cell {
        q: 2,
        r: -2,
        ring: 2,
        data_index: 3,
    },
    Cell {
        q: 2,
        r: -1,
        ring: 2,
        data_index: 4,
    },
    Cell {
        q: 2,
        r: 0,
        ring: 2,
        data_index: 5,
    },
    Cell {
        q: 1,
        r: 1,
        ring: 2,
        data_index: 6,
    },
    Cell {
        q: 0,
        r: 2,
        ring: 2,
        data_index: 7,
    },
    Cell {
        q: -1,
        r: 2,
        ring: 2,
        data_index: 8,
    },
    Cell {
        q: -2,
        r: 2,
        ring: 2,
        data_index: 9,
    },
    Cell {
        q: -2,
        r: 1,
        ring: 2,
        data_index: 10,
    },
    Cell {
        q: -2,
        r: 0,
        ring: 2,
        data_index: 11,
    },
    Cell {
        q: -2,
        r: -1,
        ring: 3,
        data_index: 12,
    },
    Cell {
        q: -1,
        r: -2,
        ring: 3,
        data_index: 13,
    },
    Cell {
        q: 0,
        r: -3,
        ring: 3,
        data_index: 14,
    },
    Cell {
        q: 1,
        r: -3,
        ring: 3,
        data_index: 15,
    },
    Cell {
        q: 2,
        r: -3,
        ring: 3,
        data_index: 16,
    },
    Cell {
        q: 3,
        r: -3,
        ring: 3,
        data_index: 17,
    },
    Cell {
        q: 3,
        r: -2,
        ring: 3,
        data_index: 18,
    },
    Cell {
        q: 3,
        r: -1,
        ring: 3,
        data_index: 19,
    },
    Cell {
        q: 3,
        r: 0,
        ring: 3,
        data_index: 20,
    },
    Cell {
        q: 2,
        r: 1,
        ring: 3,
        data_index: 21,
    },
    Cell {
        q: 1,
        r: 2,
        ring: 3,
        data_index: 22,
    },
    Cell {
        q: 0,
        r: 3,
        ring: 3,
        data_index: 23,
    },
    Cell {
        q: -1,
        r: 3,
        ring: 3,
        data_index: 24,
    },
    Cell {
        q: -2,
        r: 3,
        ring: 3,
        data_index: 25,
    },
    Cell {
        q: -3,
        r: 3,
        ring: 3,
        data_index: 26,
    },
    Cell {
        q: -3,
        r: 2,
        ring: 3,
        data_index: 27,
    },
    Cell {
        q: -3,
        r: 1,
        ring: 3,
        data_index: 28,
    },
    Cell {
        q: -3,
        r: 0,
        ring: 3,
        data_index: 29,
    },
    Cell {
        q: -3,
        r: -1,
        ring: 4,
        data_index: 30,
    },
    Cell {
        q: -2,
        r: -2,
        ring: 4,
        data_index: 31,
    },
    Cell {
        q: -1,
        r: -3,
        ring: 4,
        data_index: 32,
    },
    Cell {
        q: 0,
        r: -4,
        ring: 4,
        data_index: 33,
    },
    Cell {
        q: 1,
        r: -4,
        ring: 4,
        data_index: 34,
    },
    Cell {
        q: 2,
        r: -4,
        ring: 4,
        data_index: 35,
    },
    Cell {
        q: 3,
        r: -4,
        ring: 4,
        data_index: 36,
    },
    Cell {
        q: 4,
        r: -4,
        ring: 4,
        data_index: 37,
    },
    Cell {
        q: 4,
        r: -3,
        ring: 4,
        data_index: 38,
    },
    Cell {
        q: 4,
        r: -2,
        ring: 4,
        data_index: 39,
    },
    Cell {
        q: 4,
        r: -1,
        ring: 4,
        data_index: 40,
    },
    Cell {
        q: 4,
        r: 0,
        ring: 4,
        data_index: 41,
    },
    Cell {
        q: 3,
        r: 1,
        ring: 4,
        data_index: 42,
    },
    Cell {
        q: 2,
        r: 2,
        ring: 4,
        data_index: 43,
    },
    Cell {
        q: 1,
        r: 3,
        ring: 4,
        data_index: 44,
    },
    Cell {
        q: 0,
        r: 4,
        ring: 4,
        data_index: 45,
    },
    Cell {
        q: -1,
        r: 4,
        ring: 4,
        data_index: 46,
    },
    Cell {
        q: -2,
        r: 4,
        ring: 4,
        data_index: 47,
    },
    Cell {
        q: -3,
        r: 4,
        ring: 4,
        data_index: 48,
    },
    Cell {
        q: -4,
        r: 4,
        ring: 4,
        data_index: 49,
    },
    Cell {
        q: -4,
        r: 3,
        ring: 4,
        data_index: 50,
    },
    Cell {
        q: -4,
        r: 2,
        ring: 4,
        data_index: 51,
    },
    Cell {
        q: -4,
        r: 1,
        ring: 4,
        data_index: 52,
    },
    Cell {
        q: -4,
        r: 0,
        ring: 4,
        data_index: 53,
    },
    Cell {
        q: -4,
        r: -1,
        ring: 5,
        data_index: 54,
    },
    Cell {
        q: -3,
        r: -2,
        ring: 5,
        data_index: 55,
    },
    Cell {
        q: -2,
        r: -3,
        ring: 5,
        data_index: 56,
    },
    Cell {
        q: -1,
        r: -4,
        ring: 5,
        data_index: 57,
    },
    Cell {
        q: 0,
        r: -5,
        ring: 5,
        data_index: 58,
    },
    Cell {
        q: 1,
        r: -5,
        ring: 5,
        data_index: 59,
    },
    Cell {
        q: 2,
        r: -5,
        ring: 5,
        data_index: 60,
    },
    Cell {
        q: 3,
        r: -5,
        ring: 5,
        data_index: 61,
    },
    Cell {
        q: 4,
        r: -5,
        ring: 5,
        data_index: 62,
    },
    Cell {
        q: 5,
        r: -5,
        ring: 5,
        data_index: 63,
    },
    Cell {
        q: 5,
        r: -4,
        ring: 5,
        data_index: 64,
    },
    Cell {
        q: 5,
        r: -3,
        ring: 5,
        data_index: 65,
    },
    Cell {
        q: 5,
        r: -2,
        ring: 5,
        data_index: 66,
    },
    Cell {
        q: 5,
        r: -1,
        ring: 5,
        data_index: 67,
    },
    Cell {
        q: 5,
        r: 0,
        ring: 5,
        data_index: 68,
    },
    Cell {
        q: 4,
        r: 1,
        ring: 5,
        data_index: 69,
    },
    Cell {
        q: 3,
        r: 2,
        ring: 5,
        data_index: 70,
    },
    Cell {
        q: 2,
        r: 3,
        ring: 5,
        data_index: 71,
    },
    Cell {
        q: 1,
        r: 4,
        ring: 5,
        data_index: 72,
    },
    Cell {
        q: 0,
        r: 5,
        ring: 5,
        data_index: 73,
    },
    Cell {
        q: -1,
        r: 5,
        ring: 5,
        data_index: 74,
    },
    Cell {
        q: -2,
        r: 5,
        ring: 5,
        data_index: 75,
    },
    Cell {
        q: -3,
        r: 5,
        ring: 5,
        data_index: 76,
    },
    Cell {
        q: -4,
        r: 5,
        ring: 5,
        data_index: 77,
    },
    Cell {
        q: -5,
        r: 5,
        ring: 5,
        data_index: 78,
    },
    Cell {
        q: -5,
        r: 4,
        ring: 5,
        data_index: 79,
    },
    Cell {
        q: -5,
        r: 3,
        ring: 5,
        data_index: 80,
    },
    Cell {
        q: -5,
        r: 2,
        ring: 5,
        data_index: 81,
    },
    Cell {
        q: -5,
        r: 1,
        ring: 5,
        data_index: 82,
    },
    Cell {
        q: -5,
        r: 0,
        ring: 5,
        data_index: 83,
    },
    Cell {
        q: -5,
        r: -1,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -4,
        r: -2,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -3,
        r: -3,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -2,
        r: -4,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -1,
        r: -5,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 0,
        r: -6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 1,
        r: -6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 2,
        r: -6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 3,
        r: -6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 4,
        r: -6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 5,
        r: -6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 6,
        r: -6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 6,
        r: -5,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 6,
        r: -4,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 6,
        r: -3,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 6,
        r: -2,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 6,
        r: -1,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 6,
        r: 0,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 5,
        r: 1,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 4,
        r: 2,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 3,
        r: 3,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 2,
        r: 4,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 1,
        r: 5,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: 0,
        r: 6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -1,
        r: 6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -2,
        r: 6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -3,
        r: 6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -4,
        r: 6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -5,
        r: 6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -6,
        r: 6,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -6,
        r: 5,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -6,
        r: 4,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -6,
        r: 3,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -6,
        r: 2,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -6,
        r: 1,
        ring: 6,
        data_index: -1,
    },
    Cell {
        q: -6,
        r: 0,
        ring: 6,
        data_index: -1,
    },
];
