/* estate-source.mjs — THE REGISTRY IS THE SOURCE.
   surfaces/index.html and surfaces/doors/*.html are generated by
   tools/build-surfaces.mjs from surfaces/estate.json. This rebuilds into a
   temp directory and fails if the committed HTML differs, so a hand-edit to a
   generated page cannot survive a gate — the edit has to happen in the
   registry, where the hub and the six doors read it together.

   Founder, 2026-08-26: "the best structural design to accommodate our
   languages stack and updates/editing forward." Two hand-kept lists of the
   same truth had already drifted once (the hub said five domains after
   bnature.bio made six). One source cannot.

   It also holds the two properties that make the language stack work:
   every generated string carries a data-i18n key, and every key in the whole
   tree exists in the corpus — a missing key is a string no tongue can ever
   reach, and it would fall back to English forever without anyone noticing. */
import { readFileSync, mkdtempSync, rmSync, readdirSync, existsSync, writeFileSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const SURF = join(ROOT, 'surfaces');

let pass = 0, fail = 0;
const ok = (name, cond, note = '') => {
  if (cond) { pass++; console.log(`PASS ${name}`); }
  else { fail++; console.log(`FAIL ${name}${note ? ' — ' + note : ''}`); }
};

/* 1 · the registry parses and is internally sound */
const E = JSON.parse(readFileSync(join(SURF, 'estate.json'), 'utf8'));
ok('the registry declares six domains', E.domains.length === 6, String(E.domains.length));
ok('every domain has an id, a slug, an accent and one thing to do',
  E.domains.every(d => d.id && d.slug && /^#[0-9A-F]{6}$/i.test(d.accent) && d.act && d.act.href && d.act.label),
  E.domains.filter(d => !(d.id && d.slug && d.act)).map(d => d.host).join(', '));
{
  const ids = new Set(E.domains.map(d => d.id));
  const strays = E.surfaces.filter(s => !ids.has(s.domain));
  ok('every surface names a domain that exists', strays.length === 0, strays.map(s => s.file).join(', '));
  const dupes = E.surfaces.map(s => s.file).filter((f, i, a) => a.indexOf(f) !== i);
  ok('every surface lands under exactly one door', dupes.length === 0, dupes.join(', '));
  const states = E.surfaces.filter(s => !['working', 'partly', 'roadmap'].includes(s.state));
  ok('every surface carries an honesty state', states.length === 0, states.map(s => s.file).join(', '));
  const missingFiles = E.surfaces.filter(s => !/^https?:/.test(s.file) &&
    !existsSync(join(SURF, s.file.endsWith('/') ? s.file + 'index.html' : s.file)));
  ok('every registered surface exists on disk', missingFiles.length === 0, missingFiles.map(s => s.file).join(', '));
}

/* 2 · THE DRIFT CHECK — the hub is generated, and regeneration must be
   idempotent (2026-08-28 update: the hub moved to scripts/build-atlas.mjs
   from the ROOT estate.json in the atlas lane; tools/build-surfaces.mjs no
   longer generates it. The doors are HAND-KEPT since the byte-true hex-band
   and A3 redesign rulings — no generator owns them, so their integrity is
   the language checks below (§3) plus estate-check's registry laws; a drift
   rebuild for them would hand-back a page the rulings superseded). What stays
   enforced here: rebuilding the hub from its registry must reproduce the
   committed page byte for byte — a hand-edit to generated output cannot
   survive, the edit has to happen in the generator. */
{
  /* build-atlas reads estate.json + doors relative to its cwd and writes
     surfaces/index.html in place — so idempotence is proven against the
     COMMITTED tree: capture HEAD's version, regenerate, compare, and
     restore HEAD if they differ so this gate never leaves mutation behind */
  const committed = execFileSync('git', ['show', 'HEAD:surfaces/index.html'], { cwd: ROOT });
  execFileSync(process.execPath, [join(ROOT, 'scripts', 'build-atlas.mjs')], { stdio: 'pipe', cwd: ROOT });
  const regenerated = readFileSync(join(SURF, 'index.html'));
  const same = Buffer.compare(Buffer.from(committed), regenerated) === 0;
  if (!same) writeFileSync(join(SURF, 'index.html'), committed);
  ok('the committed hub matches its registry regeneration (byte for byte)', same,
     same ? '' : 'run: node scripts/build-atlas.mjs and commit');
}

/* 3 · THE LANGUAGE STACK — every string reachable by every tongue */
{
  var walk = (d, b = '') => readdirSync(d, { withFileTypes: true }).flatMap(e => {
    const r = b ? b + '/' + e.name : e.name;
    if (e.isDirectory()) return e.name === 'fleet' ? [] : walk(join(d, e.name), r);
    return e.name.endsWith('.html') ? [r] : [];
  });
  const keys = new Set();
  for (const f of walk(SURF)) {
    for (const m of readFileSync(join(SURF, f), 'utf8').matchAll(/data-i18n="([^"]+)"/g)) keys.add(m[1]);
  }
  const corpus = JSON.parse(readFileSync(join(SURF, 'lang-corpus.json'), 'utf8'));
  const have = new Set(Object.keys(corpus.strings));
  const missing = [...keys].filter(k => !have.has(k));
  ok(`every data-i18n key in the tree exists in the corpus (${keys.size} keys)`,
    missing.length === 0,
    missing.length ? missing.length + ' missing, e.g. ' + missing.slice(0, 6).join(', ') : '');

  /* a language that carries only half the corpus is worse than one that
     carries none, because the page looks translated and is not. Count it. */
  const langs = corpus._meta.langs;
  const thin = langs.map(L => {
    const n = [...have].filter(k => corpus.strings[k][L]).length;
    return { L, n, pct: Math.round(n / have.size * 100) };
  }).filter(x => x.pct < 100);
  ok(`every docked tongue covers the whole corpus (${langs.length} languages, ${have.size} keys)`,
    thin.length === 0,
    thin.map(x => `${x.L} ${x.pct}%`).join(', '));

  /* THE STALE-TRANSLATION CHECK. A key whose ENGLISH changed on the page but
     not in the corpus is worse than an untranslated key: the page looks
     translated and describes something that is no longer true. Tonight the
     kandi bar gained a third arm and 26 tongues went on saying "THE TWO ARMS",
     and four surfaces rendered one key with two different Englishes — the hub
     tile's name and the door tile's verb — so a translated reader got
     whichever one the corpus happened to hold, in the wrong place. Neither was
     visible to any gate. Compare what the page says in English to what the
     corpus thinks English is. */
  {
    const dec = t => t.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&ldquo;|&rdquo;/g, '\u201C')
      .replace(/\s+/g, ' ').trim();
    const drift = [], seen = {};
    for (const f of walk(SURF)) {
      const html = readFileSync(join(SURF, f), 'utf8');
      for (const m of html.matchAll(/data-i18n="([^"]+)"[^>]*>([^<]*)</g)) {
        const k = m[1], t = dec(m[2]);
        if (!t) continue;
        /* one key must render ONE English everywhere it appears */
        if (seen[k] && seen[k].t !== t) drift.push(k + ': two Englishes (' + seen[k].f + ' vs ' + f + ')');
        else if (!seen[k]) seen[k] = { t, f };
        const e = corpus.strings[k];
        if (e && e.en && dec(e.en) !== t) drift.push(k + ' in ' + f + ': corpus English is stale');
      }
    }
    const uniq = [...new Set(drift)];
    ok('the corpus English matches what the pages actually say',
      uniq.length === 0,
      uniq.length ? uniq.length + ' drifted: ' + uniq.slice(0, 4).join(' · ') : '');
  }

  const generated = [...keys].filter(k => /^(s|d|m|hub)\./.test(k));
  ok('the generated pages are translatable (they carry i18n keys)',
    generated.length > 100, String(generated.length));
}

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
