/* estate-source.mjs — THE REGISTRY IS THE SOURCE.
   surfaces/index.html and surfaces/doors/*.html are generated by
   tools/build-surfaces.mjs from surfaces/estate.json. This rebuilds into a
   temp directory and fails if the committed HTML differs, so a hand-edit to a
   generated page cannot survive a gate — the edit has to happen in the
   registry, where the hub and the six doors read it together.

   Founder, 2026-08-26: "the best structural design to accommodate our
   languages stack and updates/editing forward." Two hand-kept lists of the
   same truth had already drifted once (the hub said five domains after
   bnature.bio made six). One source cannot.

   It also holds the two properties that make the language stack work:
   every generated string carries a data-i18n key, and every key in the whole
   tree exists in the corpus — a missing key is a string no tongue can ever
   reach, and it would fall back to English forever without anyone noticing. */
import { readFileSync, mkdtempSync, rmSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const SURF = join(ROOT, 'surfaces');

let pass = 0, fail = 0;
const ok = (name, cond, note = '') => {
  if (cond) { pass++; console.log(`PASS ${name}`); }
  else { fail++; console.log(`FAIL ${name}${note ? ' — ' + note : ''}`); }
};

/* 1 · the registry parses and is internally sound */
const E = JSON.parse(readFileSync(join(SURF, 'estate.json'), 'utf8'));
ok('the registry declares six domains', E.domains.length === 6, String(E.domains.length));
ok('every domain has an id, a slug, an accent and one thing to do',
  E.domains.every(d => d.id && d.slug && /^#[0-9A-F]{6}$/i.test(d.accent) && d.act && d.act.href && d.act.label),
  E.domains.filter(d => !(d.id && d.slug && d.act)).map(d => d.host).join(', '));
{
  const ids = new Set(E.domains.map(d => d.id));
  const strays = E.surfaces.filter(s => !ids.has(s.domain));
  ok('every surface names a domain that exists', strays.length === 0, strays.map(s => s.file).join(', '));
  const dupes = E.surfaces.map(s => s.file).filter((f, i, a) => a.indexOf(f) !== i);
  ok('every surface lands under exactly one door', dupes.length === 0, dupes.join(', '));
  const states = E.surfaces.filter(s => !['working', 'partly', 'roadmap'].includes(s.state));
  ok('every surface carries an honesty state', states.length === 0, states.map(s => s.file).join(', '));
  const missingFiles = E.surfaces.filter(s => !/^https?:/.test(s.file) &&
    !existsSync(join(SURF, s.file.endsWith('/') ? s.file + 'index.html' : s.file)));
  ok('every registered surface exists on disk', missingFiles.length === 0, missingFiles.map(s => s.file).join(', '));
}

/* 2 · THE DRIFT CHECK — rebuild and compare, byte for byte */
{
  const tmp = mkdtempSync(join(tmpdir(), 'estate-'));
  try {
    execFileSync(process.execPath, [join(ROOT, 'tools', 'build-surfaces.mjs'), '--out', tmp], { stdio: 'pipe' });
    const rel = ['index.html', ...readdirSync(join(tmp, 'doors')).map(f => 'doors/' + f)];
    const drifted = [];
    for (const r of rel) {
      const a = readFileSync(join(tmp, r), 'utf8');
      const b = existsSync(join(SURF, r)) ? readFileSync(join(SURF, r), 'utf8') : null;
      if (b === null) { drifted.push(r + ' (missing)'); continue; }
      if (a !== b) {
        // name the first differing line so the fix is obvious
        const A = a.split('\n'), B = b.split('\n');
        let i = 0; while (i < A.length && i < B.length && A[i] === B[i]) i++;
        drifted.push(`${r} (line ${i + 1})`);
      }
    }
    ok(`the committed pages match the registry (${rel.length} generated files)`,
      drifted.length === 0,
      drifted.length ? drifted.join(', ') + ' — run: node tools/build-surfaces.mjs' : '');
  } finally { rmSync(tmp, { recursive: true, force: true }); }
}

/* 3 · THE LANGUAGE STACK — every string reachable by every tongue */
{
  const walk = (d, b = '') => readdirSync(d, { withFileTypes: true }).flatMap(e => {
    const r = b ? b + '/' + e.name : e.name;
    if (e.isDirectory()) return e.name === 'fleet' ? [] : walk(join(d, e.name), r);
    return e.name.endsWith('.html') ? [r] : [];
  });
  const keys = new Set();
  for (const f of walk(SURF)) {
    for (const m of readFileSync(join(SURF, f), 'utf8').matchAll(/data-i18n="([^"]+)"/g)) keys.add(m[1]);
  }
  const corpus = JSON.parse(readFileSync(join(SURF, 'lang-corpus.json'), 'utf8'));
  const have = new Set(Object.keys(corpus.strings));
  const missing = [...keys].filter(k => !have.has(k));
  ok(`every data-i18n key in the tree exists in the corpus (${keys.size} keys)`,
    missing.length === 0,
    missing.length ? missing.length + ' missing, e.g. ' + missing.slice(0, 6).join(', ') : '');

  /* a language that carries only half the corpus is worse than one that
     carries none, because the page looks translated and is not. Count it. */
  const langs = corpus._meta.langs;
  const thin = langs.map(L => {
    const n = [...have].filter(k => corpus.strings[k][L]).length;
    return { L, n, pct: Math.round(n / have.size * 100) };
  }).filter(x => x.pct < 100);
  ok(`every docked tongue covers the whole corpus (${langs.length} languages, ${have.size} keys)`,
    thin.length === 0,
    thin.map(x => `${x.L} ${x.pct}%`).join(', '));

  const generated = [...keys].filter(k => /^(s|d|m|hub)\./.test(k));
  ok('the generated pages are translatable (they carry i18n keys)',
    generated.length > 100, String(generated.length));
}

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
