import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {webcrypto,createHash} from 'node:crypto';
const page=readFileSync('surfaces/plur.html','utf8'),quality=JSON.parse(readFileSync('assets/plur-voices/quality.json')),comparison=JSON.parse(readFileSync('assets/plur-voices/comparison/manifest.json'));
const source=[...page.matchAll(/<script\b[^>]*>([^]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes("var root=document.getElementById('plurReview')"));
const hash=b=>createHash('sha256').update(b).digest('hex');
test('every comparison binds existing text and both recordings; translation drafts pin source revisions',()=>{for(const e of comparison.entries){const original=quality.entries.find(x=>x.id===e.id);assert.equal(e.text,original.text);assert.equal(hash(readFileSync('assets/plur-voices/'+original.file)),e['baselineSha256_PUBLIC-CONSTANT']);const b=readFileSync('assets/plur-voices/comparison/'+e.candidate);assert.equal(hash(b),e['candidateSha256_PUBLIC-CONSTANT']);assert.equal(b.toString('ascii',0,4),'RIFF');assert.ok(e.durationSeconds>.1);assert.equal(e.review,'unreviewed candidate');}const t=JSON.parse(readFileSync('assets/plur-voices/comparison/translations.json'));assert.equal(t.models.length,2);for(const m of t.models){assert.match(m.revision,/^[a-f0-9]{40}$/);assert.equal(m.entries.length,4);for(const e of m.entries)assert.equal(e.review,'machine draft; native review pending');}});
async function fixture(tamper=false){const nodes=new Map(),downloads=[];function element(){return {value:'',options:[{},{}],children:[],listeners:{},textContent:'',pause(){},removeAttribute(){},addEventListener(k,fn){this.listeners[k]=fn;},appendChild(e){this.children.push(e);},click(){if(this.download)downloads.push(this.download);},querySelector(){return button;}};}const button=element();const node=id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};
const sandbox={document:{getElementById:node,createElement:element},window:{addEventListener(){}},crypto:webcrypto,Blob,URL:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}},setTimeout:fn=>fn(),fetch:async url=>{const file=String(url).split('?')[0].replace('../','');if(file.endsWith('.json'))return {ok:true,json:async()=>JSON.parse(readFileSync(file))};let b=readFileSync(file);if(tamper)b=Buffer.from('wrong bytes');return {ok:true,arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)};}};
vm.runInNewContext(source,sandbox);await new Promise(r=>setImmediate(r));const pick=comparison.entries[0];node('reviewItem').value=pick.id;node('reviewItem').listeners.change();node('reviewerName').value='Automated fixture';node('reviewerDialect').value='test';node('reviewRating').value='unsure';node('reviewNotes').value='UI test, not a linguistic review';await node('speakerReviewForm').listeners.submit({preventDefault(){},currentTarget:node('speakerReviewForm')});return {nodes,downloads};}
test('speaker review exports a draft only after both exact audio hashes match',async()=>{const r=await fixture();assert.equal(r.downloads.length,1);assert.match(r.nodes.get('reviewStatus').textContent,/not been submitted or marked as approved/);assert.equal(r.nodes.get('reviewItem').children.length,109);});
test('changed audio refuses review export',async()=>{const r=await fixture(true);assert.equal(r.downloads.length,0);assert.match(r.nodes.get('reviewStatus').textContent,/Audio changed/);assert.equal(r.nodes.get('reviewItem').disabled,false);});
