FROM caddy:2.11.4-builder AS builder
ENV GOMAXPROCS=2 GOFLAGS=-p=2
RUN xcaddy build v2.11.4 --with github.com/mholt/caddy-ratelimit@v0.1.0
FROM caddy:2.11.4
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
