#!/usr/bin/env node
// build-skaists.mjs — compiles the estate's design system (docs/design/skaists/tokens.json,
// "skaists", graded A- 2026-09-19) into surfaces/skaists.css. ONE source of truth: surfaces
// never hand-pick a hex, a size or a corner; they use these variables and type classes.
//
//   --sk-<colour>      every colour token, per register (new bee on :root; raver and cypherpunk
//                      ride body[data-reg] / html[data-reg], the estate contract). {refs} resolved.
//   --sk-font-<family> the named stacks (house, bee-serif, bee-sans, raver-display, raver-body, mono, ui)
//   .sk-<style>        every type style (bee-display, raver-action, cypher-body, house-name …)
//   --sk-s1..s6, --sk-radius*, --sk-control-*, --sk-glow-*, --sk-rainbow, --sk-flow/hatch
//   @font-face         the faces, self-hosted (fonts/eternal/*, fonts/burti.woff2): no font CDN.
//
// Run: node scripts/build-skaists.mjs            (writes surfaces/skaists.css)
//      node scripts/build-skaists.mjs --check    (exit 1 if the committed file is stale)
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const T = JSON.parse(readFileSync(join(ROOT, 'docs/design/skaists/tokens.json'), 'utf8'));
const FONTS = readFileSync(join(ROOT, 'surfaces/fonts/eternal-fonts.css'), 'utf8')
  .split('\n').filter(l => l.startsWith('@font-face')).map(l => l.replace(/url\(eternal\//g, 'url(fonts/eternal/'));
const REGS = T.color.themes.map(t => t.id); // bee, raver, cypherpunk

// resolve {ref} values per register
const byName = Object.fromEntries(T.color.tokens.map(t => [t.name, t]));
function resolve(name, reg, seen = new Set()) {
  if (seen.has(name)) throw new Error('token cycle at ' + name);
  seen.add(name);
  const v = byName[name].value[reg];
  const m = /^\{([\w-]+)\}$/.exec(v);
  return m ? resolve(m[1], reg, seen) : v.toLowerCase();
}
const colours = reg => T.color.tokens.map(t => `--sk-${t.name}:${resolve(t.name, reg)}`);
const perReg = (tokens, reg) => tokens.flatMap(t => typeof t.value === 'object' ? [`--sk-${t.name}:${t.value[reg]}`] : []);
const flat = tokens => tokens.filter(t => typeof t.value !== 'object').map(t => `--sk-${t.name}:${t.value}`);

const fam = T.type.families;
const families = Object.entries(fam).map(([k, v]) => `--sk-font-${k}:${v}`);
const styles = [];
for (const g of T.type.groups) for (const s of g.styles) {
  const f = s.family || g.family;
  styles.push(`.sk-${s.name}{font:${s.fontWeight} ${s.fontSize}/${s.lineHeight} var(--sk-font-${f})${s.letterSpacing ? `;letter-spacing:${s.letterSpacing}` : ''}}`);
}
const sel = reg => `:is(html,body)[data-reg="${reg}"]`;
const out = [
  '/* skaists.css — GENERATED by scripts/build-skaists.mjs from docs/design/skaists/tokens.json.',
  '   Do not edit by hand: change the tokens and rebuild (CI checks it is fresh).',
  '   new bee is the default; raver and cypherpunk ride [data-reg] on <html> or <body>. */',
  ...FONTS,
  '@font-face{font-family:\'burti\';font-style:normal;font-weight:400;font-display:swap;src:url(fonts/burti.woff2) format(\'woff2\')}',
  `:root{${[...colours('bee'), ...families, ...flat(T.spacing.tokens), ...flat(T.radius.tokens), ...flat(T.control.tokens), ...perReg(T.shadow.tokens, 'bee'), ...flat(T.gradient.tokens), ...flat(T.direction.tokens)].join(';')}}`,
  ...REGS.filter(r => r !== 'bee').map(r => `${sel(r)}{${[...colours(r), ...perReg(T.shadow.tokens, r)].join(';')}}`),
  '[dir="rtl"]{--sk-flow:270deg;--sk-hatch:135deg}',
  ...styles,
  '' ].join('\n');

const dest = join(ROOT, 'surfaces/skaists.css');
if (process.argv.includes('--check')) {
  let cur = ''; try { cur = readFileSync(dest, 'utf8'); } catch {}
  if (cur !== out) { console.error('skaists.css is stale: run node scripts/build-skaists.mjs and commit'); process.exit(1); }
  console.log('skaists.css matches tokens.json'); process.exit(0);
}
writeFileSync(dest, out);
console.log(`skaists.css — ${T.color.tokens.length} colours x ${REGS.length} registers · ${styles.length} type styles · ${FONTS.length + 1} faces`);
