// gen_vk_count_cpp.js — vk.json → vk_count_constants.hpp for count.circom's
// verifier (copy of ../privacy/gen_vk_cpp.js with ONLY the provenance lines
// and defaults changed — the byte-level logic is the M4-lane's, tested by
// its gates; decimal byte arrays per the repo's hex-run law; projective →
// affine; G2 word order EIP-197).
const fs = require('fs');
const vk = JSON.parse(fs.readFileSync(process.argv[2] || '/home/travi/plonkport/count_vk.json', 'utf8'));
if (vk.protocol !== 'plonk' || vk.curve !== 'bn128') throw new Error('not a bn128 plonk vk');

const Q  = 21888242871839275222246405745257275088548364400416034343698204186575808495617n; // PUBLIC-CONSTANT BN254 scalar field
const QF = 21888242871839275222246405745257275088696311157297823662689037894645226208583n; // PUBLIC-CONSTANT BN254 base field
const G2GEN = [ // PUBLIC-CONSTANT BN254 G2 generator, [x_c0, x_c1, y_c0, y_c1]
  10857046999023057135944570762232829481370756359578518086990519993285655852781n,   // PUBLIC-CONSTANT public chain constant / test vector (hex-run law)
  11559732032986387107991004021392285783925812861821192530917403151452391805634n,   // PUBLIC-CONSTANT public chain constant / test vector (hex-run law)
  8495653923123431417604973247489272438418190587263600148770280649306958101930n,   // PUBLIC-CONSTANT public chain constant / test vector (hex-run law)
  4082367875863433681332203403145435568316851327593401208105741076214120093531n,   // PUBLIC-CONSTANT public chain constant / test vector (hex-run law)
];

const be = (v, n) => { const b = []; for (let i = n - 1; i >= 0; --i) b.push(Number((v >> BigInt(8 * i)) & 255n)); return b; };
const decArr = (bytes, per) => {
   const parts = [];
   for (let i = 0; i < bytes.length; i += per) parts.push('   ' + bytes.slice(i, i + per).join(',') + ',');
   return '\n' + parts.join('\n');
};
const inv = (a, m) => {
   let t = 0n, nt = 1n, r = m, nr = a % m;
   while (nr) { const q = r / nr; [t, nt] = [nt, t - q * nt]; [r, nr] = [nr, r - q * nr]; }
   if (t < 0n) t += m; return t;
};
const affine = (p, m) => {
   let [x, y, z] = [BigInt(p[0]), BigInt(p[1]), BigInt(p[2] ?? 1n)];
   if (z !== 1n) { const zi = inv(z % m, m); x = x * zi % m; y = y * zi % m; }
   return [x % m, y % m];
};

const P = v => { const [x, y] = affine(v, QF); return be(x, 32).concat(be(y, 32)); };
const S = v => be(BigInt(v) % Q, 32);
const g2 = ([c0x, c1x, c0y, c1y]) => be(c1x, 32).concat(be(c0x, 32), be(c1y, 32), be(c0y, 32));

const h = [];
h.push('// vk_count_constants.hpp — GENERATED by gen_vk_count_cpp.js from count_vk.json. DO NOT EDIT BY HAND.');
h.push('// Provenance: circuit count.circom (64-leaf full-tree Poseidon count fold,');
h.push('// SPEC-ZK-RECEIPT-AGGREGATES-1 v1), powersoftau bn128 pot' + vk.power + ' with ONE');
h.push('// honest participant (rehearsal seat, 2026-10-06), snarkjs 0.7.6 plonk setup,');
h.push('// nPublic ' + vk.nPublic + ' (root, kind, count).');
h.push('// Regenerate: node gen_vk_count_cpp.js /path/to/vk.json vk_count_constants.hpp');
h.push('#pragma once');
h.push('');
h.push('static constexpr int N_PUBLIC = ' + vk.nPublic + ';');
h.push('static constexpr int PL_POWER = ' + vk.power + ';   // n = 2^PL_POWER rows');
h.push('');
for (const [k, v] of [['QM', vk.Qm], ['QL', vk.Ql], ['QR', vk.Qr], ['QO', vk.Qo], ['QC', vk.Qc], ['S1', vk.S1], ['S2', vk.S2], ['S3', vk.S3]]) {
   h.push('static constexpr unsigned char VK_' + k + '[64] = {' + decArr(P(v), 16) + '\n};');
   h.push('');
}
h.push('static constexpr unsigned char VK_X2[128] = {' + decArr(g2([BigInt(vk.X_2[0][0]), BigInt(vk.X_2[0][1]), BigInt(vk.X_2[1][0]), BigInt(vk.X_2[1][1])]).map(x => x), 16) + '\n};');
h.push('');
h.push('static constexpr unsigned char VK_W1[32] = {' + decArr(S(vk.w), 16) + '\n};');
h.push('static constexpr unsigned char VK_K1[32] = {' + decArr(S(vk.k1), 16) + '\n};');
h.push('static constexpr unsigned char VK_K2[32] = {' + decArr(S(vk.k2), 16) + '\n};');
h.push('');
h.push('// chain constants (independent of the vk)');
h.push('static constexpr unsigned char PL_Q[32] = {' + decArr(be(Q, 32), 16) + '\n};');
h.push('static constexpr unsigned char PL_QF[32] = {' + decArr(be(QF, 32), 16) + '\n};');
h.push('static constexpr unsigned char PL_G1GEN[64] = {' + decArr(be(1n, 32).concat(be(2n, 32)), 16) + '\n};');
h.push('static constexpr unsigned char PL_G2GEN[128] = {' + decArr(g2(G2GEN), 16) + '\n};');
h.push('');
fs.writeFileSync(process.argv[3] || 'vk_count_constants.hpp', h.join('\n'));
console.log('vk_count_constants.hpp written: power', vk.power, 'nPublic', vk.nPublic);
