//! Pinned ABI constants and keccak256.
//!
//! Source pins (all read 2026-09-12, offline):
//! - WithAutonomi/evmlib tag `v0.9.1`, `contracts/IPaymentVaultV2.sol`
//!   (event + errors), `contracts/PaymentVaultV2.sol` (MAX_MERKLE_DEPTH,
//!   CANDIDATES_PER_POOL, `payForMerkleTree` body),
//!   `contracts/MerklePaymentLib.sol` (`expectedRewardPools`,
//!   `selectWinnerPool`, `selectWinnerNodes`, `median16`),
//!   `abi/IPaymentVault.json` (the exact type strings below),
//!   `src/merkle_payments/merkle_tree.rs:28` (MERKLE_PAYMENT_EXPIRATION).
//!
//! The selectors/topics are COMPUTED from the pinned signature strings at
//! runtime (never hand-pasted literals that could drift); the parity tests
//! pin the resulting bytes against vectors generated by evmlib v0.9.1's own
//! keyless helper (see `tests/parity_calldata.rs` and
//! `dev/gen-parity-vectors/`).

use sha3::{Digest, Keccak256};
use std::sync::OnceLock;

pub fn keccak256(bytes: &[u8]) -> [u8; 32] {
    let mut h = Keccak256::new();
    h.update(bytes);
    h.finalize().into()
}

fn selector(sig: &str) -> [u8; 4] {
    keccak256(sig.as_bytes())[0..4].try_into().expect("4 bytes")
}

/// `payForMerkleTree(uint8,(bytes32,(address,uint256)[16])[],uint64)` —
/// canonical type string exactly as carried by the pinned `abi/IPaymentVault.json`.
pub const PAY_FOR_MERKLE_TREE_SIG: &str =
    "payForMerkleTree(uint8,(bytes32,(address,uint256)[16])[],uint64)";

/// `approve(address,uint256)` (ERC-20) — used for the BOUNDED approval only.
pub const APPROVE_SIG: &str = "approve(address,uint256)";

/// `getCompletedMerklePayment(bytes32)` — completed-payment read-back.
pub const GET_COMPLETED_SIG: &str = "getCompletedMerklePayment(bytes32)";

/// `MerklePaymentMade(bytes32,uint8,uint256,uint64)` — the binding event.
pub const MERKLE_PAYMENT_MADE_SIG: &str = "MerklePaymentMade(bytes32,uint8,uint256,uint64)";

/// `PaymentAlreadyExists(bytes32)` — the double-payment fence revert.
pub const PAYMENT_ALREADY_EXISTS_SIG: &str = "PaymentAlreadyExists(bytes32)";

pub fn pay_for_merkle_tree_selector() -> [u8; 4] {
    static S: OnceLock<[u8; 4]> = OnceLock::new();
    *S.get_or_init(|| selector(PAY_FOR_MERKLE_TREE_SIG))
}

pub fn approve_selector() -> [u8; 4] {
    static S: OnceLock<[u8; 4]> = OnceLock::new();
    *S.get_or_init(|| selector(APPROVE_SIG))
}

pub fn get_completed_selector() -> [u8; 4] {
    static S: OnceLock<[u8; 4]> = OnceLock::new();
    *S.get_or_init(|| selector(GET_COMPLETED_SIG))
}

pub fn merkle_payment_made_topic0() -> [u8; 32] {
    static T: OnceLock<[u8; 32]> = OnceLock::new();
    *T.get_or_init(|| keccak256(MERKLE_PAYMENT_MADE_SIG.as_bytes()))
}

pub fn payment_already_exists_selector() -> [u8; 4] {
    static S: OnceLock<[u8; 4]> = OnceLock::new();
    *S.get_or_init(|| selector(PAYMENT_ALREADY_EXISTS_SIG))
}

/// Contract-side maximum Merkle depth — `PaymentVaultV2.sol` line 37
/// (`uint8 public constant MAX_MERKLE_DEPTH = 12;`).
///
/// PIN DISCREPANCY (flagged for review): evmlib v0.9.1's Rust-side
/// `merkle_batch_payment.rs` pins `MAX_MERKLE_DEPTH: u8 = 8`. The contract
/// accepts up to 12; the client library was generating trees to 8 at this
/// pin. This module enforces the CONTRACT bound (12) as the outer legal
/// limit; depth must additionally be >= 1 (`payForMerkleTree` divides
/// `totalAmount / depth` — depth 0 reverts with division by zero).
pub const MAX_MERKLE_DEPTH: u8 = 12;
pub const MIN_MERKLE_DEPTH: u8 = 1;

/// Fixed candidates-per-pool — `PaymentVaultV2.sol` line 40.
pub const CANDIDATES_PER_POOL: usize = 16;

/// Client-side payment-timestamp expiration window — evmlib v0.9.1
/// `src/merkle_payments/merkle_tree.rs:28`
/// (`pub const MERKLE_PAYMENT_EXPIRATION: u64 = 7 * 24 * 60 * 60;`),
/// enforced by `validate_payment_timestamp` in the same file (rejects
/// future timestamps and age > window). The pinned Anvil vault contract
/// itself does NOT check timestamp age; the expiry law is client-side at
/// this pin, so this module enforces it at plan/attempt validation time.
pub const MERKLE_PAYMENT_EXPIRATION_SECS: u64 = 7 * 24 * 60 * 60;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn selectors_derive_from_pinned_signatures() {
        // The parity vectors pin the actual bytes: evmlib v0.9.1 calldata
        // begins 5460f240 (tests/parity_calldata.rs asserts byte-equality
        // on the full calldata); approve(address,uint256) = 095ea7b3 is the
        // ERC-20 constant. 0x095ea7b3 // PUBLIC-CONSTANT: well-known ERC-20 approve selector
        assert_eq!(hex::encode(pay_for_merkle_tree_selector()), "5460f240");
        assert_eq!(hex::encode(approve_selector()), "095ea7b3");
    }
}
