/* mission-seed.js — GENERATED by scripts/build-missions-seed.mjs. Do not hand-edit.
   The deterministic seed ledger for the LOVErnment mission surfaces. Fixture
   figures (testnet accounting), modelled on real lanes; the receipt chain is
   sha-256 verified by mission-core.js on every load. */
(typeof window!=="undefined"?window:globalThis).BNR_MISSION_SEED = {
 "v": 1,
 "currency": "testnet accounting · USD-denominated fixtures — no token moves on these surfaces; the ERC20i treasury is a later rail",
 "fixture_note": "SEED LEDGER — demonstration data modelled on real lanes (PR #75 music-room adoption; watch-room POC; autonomi fence readiness). Every figure is a fixture, not a measurement. Local edits live in your browser only.",
 "missions": [
  {
   "mission": {
    "id": "bnr-op-2026-001",
    "title": "Improve Raver music-room adoption",
    "objective": "Ship and verify the redesigned music surface"
   },
   "team": {
    "lead": "bAiGent-01",
    "agents": [
     {
      "model": "gpt-6-astra",
      "role": "architecture"
     },
     {
      "model": "glm-5.3",
      "role": "implementation"
     },
     {
      "model": "grok",
      "role": "creative-review"
     },
     {
      "model": "fable",
      "role": "research"
     }
    ],
    "human_attending": "founder · LOViS"
   },
   "resources": {
    "api_estimate": {
     "by_model": {
      "astra": {
       "in": 12,
       "out": 3,
       "reason": 2
      },
      "glm": {
       "in": 40,
       "out": 9,
       "reason": 6
      },
      "grok": {
       "in": 6,
       "out": 1.5,
       "reason": 0.8
      },
      "fable": {
       "in": 8,
       "out": 2,
       "reason": 1
      }
     }
    },
    "compute": {
     "runtime_hours": 60,
     "storage_gb": 8,
     "bandwidth_gb": 12
    },
    "external_services": [],
    "human_review_hours": 6,
    "contingency_percent": 10,
    "tithe_percent": 10
   },
   "controls": {
    "spending_ceiling": 70,
    "milestone_release": true,
    "production_access": false,
    "secrets_access": false,
    "human_escalation_required_for": [
     "spending_above_ceiling",
     "production_changes",
     "legal_or_rights_claims",
     "irreversible_transactions"
    ]
   },
   "review": {
    "verdict": "approved",
    "reviewer": "independent-review · astra",
    "ts": "2026-09-12T19:40:00Z",
    "note": "value, feasibility and conflict checks passed; ceiling recommended at the requested total rounded up"
   },
   "milestones": [
    {
     "id": "M1",
     "title": "three-view redesign live on main",
     "deliverable": "music.html — bee / raver / cypherpunk, one set of facts",
     "release_usd": 23.04,
     "state": "released"
    },
    {
     "id": "M2",
     "title": "corpus keys ×29 tongues",
     "deliverable": "music.* strings machine-drafted into lang-corpus.json",
     "release_usd": 17.28,
     "state": "released"
    },
    {
     "id": "M3",
     "title": "independent verification + final report",
     "deliverable": "e2e walk of all three views, receipts compared",
     "release_usd": 17.28,
     "state": "released"
    }
   ],
   "work_units": [
    {
     "id": "W1",
     "title": "manifest reader + store read adapters",
     "agent": "gpt-6-astra",
     "state": "done",
     "artifacts": [
      "surfaces/manifest-reader.js",
      "surfaces/store-reader.js"
     ]
    },
    {
     "id": "W2",
     "title": "three-view surface + BNR color law",
     "agent": "glm-5.3",
     "state": "done",
     "artifacts": [
      "surfaces/music.html"
     ]
    },
    {
     "id": "W3",
     "title": "old-address redirect shim",
     "agent": "glm-5.3",
     "state": "done",
     "artifacts": [
      "surfaces/jams.html"
     ]
    },
    {
     "id": "W4",
     "title": "floor vocabulary attestation pass",
     "agent": "grok",
     "state": "done",
     "artifacts": [
      "docs/RAVER-REGISTER-LAW.md"
     ]
    },
    {
     "id": "W5",
     "title": "adoption research brief",
     "agent": "fable",
     "state": "done",
     "artifacts": [
      "docs/dispatches/"
     ]
    }
   ],
   "state": "complete",
   "finance": {
    "operating_cost_estimate": 57.6,
    "contingency_reserve": 5.76,
    "bnr_tithe": 6.34,
    "requested_total": 69.7,
    "currency": "ERC20i/testnet or fiat-denominated accounting",
    "_worksheet": {
     "api_by_model": {
      "astra": 21.6,
      "glm": 18.6,
      "grok": 5.04,
      "fable": 4.4
     },
     "api_total": 49.64,
     "tokens": {
      "input_m": 66,
      "output_m": 15.5,
      "reasoning_m": 9.8
     },
     "compute": 7.96,
     "external": 0,
     "operating_cost_estimate": 57.6,
     "contingency_reserve": 5.76,
     "bnr_tithe": 6.34,
     "requested_total": 69.7,
     "human_review_hours": 6,
     "currency": "testnet accounting · USD-denominated fixtures — no token moves on these surfaces; the ERC20i treasury is a later rail"
    }
   },
   "final_report": {
    "projected": {
     "operating_cost_estimate": 57.6,
     "contingency_reserve": 5.76,
     "bnr_tithe": 6.34,
     "requested_total": 69.7
    },
    "actual": {
     "total_spend": 59.04,
     "tithe_paid": 5.9,
     "unused_ceiling": 10.96
    },
    "milestones_planned": 3,
    "milestones_delivered": 3,
    "unverified_claims": 0,
    "variance_note": "actuals tracked under projection — the e2e compute came in cheaper than the worksheet feared; every figure on this report is a fixture, not an invoice"
   }
  },
  {
   "mission": {
    "id": "bnr-op-2026-002",
    "title": "Watch-room second screen",
    "objective": "Prove two cameras in the watch room without doubling the meter bill"
   },
   "team": {
    "lead": "bAiGent-01",
    "agents": [
     {
      "model": "gpt-6-astra",
      "role": "architecture"
     },
     {
      "model": "glm-5.3",
      "role": "implementation"
     }
    ],
    "human_attending": "founder · LOViS"
   },
   "resources": {
    "api_estimate": {
     "by_model": {
      "astra": {
       "in": 9,
       "out": 2,
       "reason": 1.5
      },
      "glm": {
       "in": 22,
       "out": 5,
       "reason": 3
      },
      "grok": {
       "in": 0,
       "out": 0,
       "reason": 0
      },
      "fable": {
       "in": 4,
       "out": 1,
       "reason": 0.5
      }
     }
    },
    "compute": {
     "runtime_hours": 34,
     "storage_gb": 20,
     "bandwidth_gb": 40
    },
    "external_services": [],
    "human_review_hours": 2,
    "contingency_percent": 10,
    "tithe_percent": 10
   },
   "controls": {
    "spending_ceiling": 0,
    "milestone_release": true,
    "production_access": false,
    "secrets_access": false,
    "human_escalation_required_for": [
     "spending_above_ceiling",
     "production_changes",
     "legal_or_rights_claims",
     "irreversible_transactions"
    ]
   },
   "review": null,
   "milestones": [
    {
     "id": "M1",
     "title": "two-camera inlet proven on the box",
     "deliverable": "second RTMP inlet + rendition ladder, receipted e2e",
     "release_usd": 20.27,
     "state": "pending"
    },
    {
     "id": "M2",
     "title": "meter pause-not-kill parity for both screens",
     "deliverable": "session receipts stay single-payer",
     "release_usd": 13.51,
     "state": "pending"
    }
   ],
   "work_units": [
    {
     "id": "W1",
     "title": "inlet topology sketch",
     "agent": "gpt-6-astra",
     "state": "queued",
     "artifacts": []
    }
   ],
   "state": "review",
   "finance": {
    "operating_cost_estimate": 33.78,
    "contingency_reserve": 3.38,
    "bnr_tithe": 3.72,
    "requested_total": 40.87,
    "currency": "ERC20i/testnet or fiat-denominated accounting",
    "_worksheet": {
     "api_by_model": {
      "astra": 15.6,
      "glm": 9.9,
      "grok": 0,
      "fable": 2.2
     },
     "api_total": 27.7,
     "tokens": {
      "input_m": 35,
      "output_m": 8,
      "reasoning_m": 5
     },
     "compute": 6.08,
     "external": 0,
     "operating_cost_estimate": 33.78,
     "contingency_reserve": 3.38,
     "bnr_tithe": 3.72,
     "requested_total": 40.87,
     "human_review_hours": 2,
     "currency": "testnet accounting · USD-denominated fixtures — no token moves on these surfaces; the ERC20i treasury is a later rail"
    }
   }
  },
  {
   "mission": {
    "id": "bnr-op-2026-003",
    "title": "Autonomi fence readiness sweep",
    "objective": "Ready the fence node for member-write verification against 0.18.1"
   },
   "team": {
    "lead": "bAiGent-01",
    "agents": [
     {
      "model": "glm-5.3",
      "role": "implementation"
     },
     {
      "model": "fable",
      "role": "research"
     }
    ],
    "human_attending": "founder · LOViS"
   },
   "resources": {
    "api_estimate": {
     "by_model": {
      "astra": {
       "in": 0,
       "out": 0,
       "reason": 0
      },
      "glm": {
       "in": 15,
       "out": 4,
       "reason": 2
      },
      "grok": {
       "in": 0,
       "out": 0,
       "reason": 0
      },
      "fable": {
       "in": 6,
       "out": 1.5,
       "reason": 0.6
      }
     }
    },
    "compute": {
     "runtime_hours": 22,
     "storage_gb": 24,
     "bandwidth_gb": 30
    },
    "external_services": [],
    "human_review_hours": 3,
    "contingency_percent": 10,
    "tithe_percent": 10
   },
   "controls": {
    "spending_ceiling": 19,
    "milestone_release": true,
    "production_access": false,
    "secrets_access": false,
    "human_escalation_required_for": [
     "spending_above_ceiling",
     "production_changes",
     "legal_or_rights_claims",
     "irreversible_transactions"
    ]
   },
   "review": {
    "verdict": "approved",
    "reviewer": "independent-review · astra",
    "ts": "2026-09-12T21:05:00Z",
    "note": "bounded sweep; ceiling set at the requested total rounded up"
   },
   "milestones": [
    {
     "id": "M1",
     "title": "pinned-version verification matrix",
     "deliverable": "observed-version table with sources",
     "release_usd": 6.01,
     "state": "funded"
    },
    {
     "id": "M2",
     "title": "member-write repro on the fence",
     "deliverable": "repro script + receipt",
     "release_usd": 4.51,
     "state": "pending"
    }
   ],
   "work_units": [
    {
     "id": "W1",
     "title": "version pin verification",
     "agent": "glm-5.3",
     "state": "active",
     "artifacts": []
    },
    {
     "id": "W2",
     "title": "deploy fence config to the prod box",
     "agent": "glm-5.3",
     "state": "blocked",
     "artifacts": []
    }
   ],
   "state": "escalated",
   "finance": {
    "operating_cost_estimate": 15.03,
    "contingency_reserve": 1.5,
    "bnr_tithe": 1.65,
    "requested_total": 18.19,
    "currency": "ERC20i/testnet or fiat-denominated accounting",
    "_worksheet": {
     "api_by_model": {
      "astra": 0,
      "glm": 7.05,
      "grok": 0,
      "fable": 3.12
     },
     "api_total": 10.17,
     "tokens": {
      "input_m": 21,
      "output_m": 5.5,
      "reasoning_m": 2.6
     },
     "compute": 4.86,
     "external": 0,
     "operating_cost_estimate": 15.03,
     "contingency_reserve": 1.5,
     "bnr_tithe": 1.65,
     "requested_total": 18.19,
     "human_review_hours": 3,
     "currency": "testnet accounting · USD-denominated fixtures — no token moves on these surfaces; the ERC20i treasury is a later rail"
    }
   }
  }
 ],
 "receipts": [
  {
   "seq": 1,
   "ts": "2026-09-12T16:02:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "proposal.draft",
   "actor": "glm-5.3",
   "summary": "mission drafted from the attending human's order — objective, team and bounds named",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "c0ae773e6dade9892a136a4c773e735599b778fa42dab3515aad4e154a49d2e6" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 2,
   "ts": "2026-09-12T16:20:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "budget.calc",
   "actor": "gpt-6-astra",
   "summary": "budget worksheet computed — api by model, compute, contingency 10%, tithe 10%",
   "cost_usd": 0,
   "artifacts": [],
   "note": "calculator: mission-core.js budget()",
   "hash": "f7ac0900bdfc9c96ec8e3caeafdd03a4baea0a980866f32b314be26a3567907e" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 3,
   "ts": "2026-09-12T16:25:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "review.submit",
   "actor": "bAiGent-01",
   "summary": "proposal submitted to independent review with the requested total",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "a959de4b3474b6f67b1a1c840840c5b6832e68465bc9157c6bfa8d4ed84b3e5c" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 4,
   "ts": "2026-09-12T19:40:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "review.verdict",
   "actor": "independent-review · astra",
   "summary": "value, feasibility and conflict checks passed — ceiling recommended",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "7da04494a36e7bd346c629cbbfa9a5aeb11bb5a8440b16c5ab747bf5d29786dc" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 5,
   "ts": "2026-09-12T20:05:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "ceiling.approve",
   "actor": "founder · LOViS",
   "summary": "spending ceiling approved — the autonomous envelope is set",
   "cost_usd": 0,
   "artifacts": [],
   "note": "human lever, logged like every other act",
   "hash": "8994107a7291ab9e13d8c3a7e4db73fb9b45c5775ba6106e33d350f60538a59e" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 6,
   "ts": "2026-09-12T20:10:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "treasury.fund",
   "actor": "dao treasury",
   "summary": "milestone M1 funded — $23.04 against the ceiling",
   "cost_usd": 23.04,
   "artifacts": [],
   "note": "testnet accounting",
   "hash": "ee221d7d07a7fb42dcef5720009e28b9c6fab1e7f1a0558f13a182087075dc18" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 7,
   "ts": "2026-09-12T20:30:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "unit.start",
   "actor": "gpt-6-astra",
   "summary": "work unit W1 started — manifest reader + store read adapters",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "03d5ded4bb8b2c92cba4dfd43835666beb5061c373ce9d89c44f04582963f471" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 8,
   "ts": "2026-09-12T22:10:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "unit.output",
   "actor": "gpt-6-astra",
   "summary": "W1 delivered — bounded readers, hash-checked, fail-closed overrides",
   "cost_usd": 0,
   "artifacts": [
    "surfaces/manifest-reader.js",
    "surfaces/store-reader.js"
   ],
   "note": "",
   "hash": "3029c644865b355594c6de35e5cdf8e5f5af275fdfbb346c1f4923208b6a544a" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 9,
   "ts": "2026-09-12T22:15:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "handoff",
   "actor": "gpt-6-astra",
   "summary": "W1 handed to glm-5.3 for the surface build",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "a457f444082670fde504af3457cc7f86d212d80d0e75e9eff48ae732f9226fc0" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 10,
   "ts": "2026-09-12T22:20:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "unit.start",
   "actor": "glm-5.3",
   "summary": "work unit W2 started — the three-view surface",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "be96b490797b93dc4346e835a68ed96bdb2c2db66cec2bed4a64162c910249c4" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 11,
   "ts": "2026-09-13T01:12:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "unit.output",
   "actor": "glm-5.3",
   "summary": "W2 delivered — bee / raver / cypherpunk render one set of facts; BNR color law named in the legend",
   "cost_usd": 0,
   "artifacts": [
    "surfaces/music.html"
   ],
   "note": "",
   "hash": "4fdedba141c9f68ed7e7c159b0016f83c91cc81463b6ec58b74c6a3c48e17d50" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 12,
   "ts": "2026-09-13T01:20:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "unit.output",
   "actor": "glm-5.3",
   "summary": "W3 delivered — old address keeps working as a redirect shim",
   "cost_usd": 0,
   "artifacts": [
    "surfaces/jams.html"
   ],
   "note": "",
   "hash": "41d699daaafea271f2cd4e9907db0b0e8db914ed8824edab01caae50c0cb151b" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 13,
   "ts": "2026-09-13T01:25:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "tool.cost",
   "actor": "glm-5.3",
   "summary": "e2e walk + register parity runs — compute metered at fixture rates",
   "cost_usd": 1.44,
   "artifacts": [],
   "note": "12 runtime hours × $0.12",
   "hash": "3774ec471428d61444ca4e49f5e80d69b89e26722e6b5a14e5f7e29da104fd1b" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 14,
   "ts": "2026-09-13T01:30:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "handoff",
   "actor": "glm-5.3",
   "summary": "W2/W3 handed to grok for creative review",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "4d0e7e7df825cdc7bed1aa30632ba64841747abfcb893f38ee22de1b98aed679" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 15,
   "ts": "2026-09-13T02:00:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "unit.output",
   "actor": "grok",
   "summary": "W4 delivered — raver register read against the native speaker's law; floor vocabulary held",
   "cost_usd": 0,
   "artifacts": [
    "docs/RAVER-REGISTER-LAW.md"
   ],
   "note": "",
   "hash": "15d158e74191a8ae5ba175fc919b1f397f32c5652bea122fa84868b249ef4aa6" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 16,
   "ts": "2026-09-13T02:40:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "verify.pass",
   "actor": "independent verification",
   "summary": "all three views walked headless — identical facts, zero page errors, crafted overrides refused fail-closed",
   "cost_usd": 0,
   "artifacts": [
    "e2e/zcode-music-check.mjs"
   ],
   "note": "",
   "hash": "86ad680c705d92674646a488dc3584f8b00d4e79b7379c0170695ba8c6dbc5e3" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 17,
   "ts": "2026-09-13T02:45:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "evaluator.continue",
   "actor": "milestone evaluator",
   "summary": "M1 verified — spend $24.48 of $70.00; release M2",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "653c07739d61779dd26c2319d2d37373b4676789344cac4e065b191c1114eead" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 18,
   "ts": "2026-09-13T02:46:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "treasury.release",
   "actor": "milestone evaluator",
   "summary": "milestone M2 released — corpus keys ×29 tongues",
   "cost_usd": 17.28,
   "artifacts": [],
   "note": "testnet accounting",
   "hash": "cee57a597611d8c997ebec4528a45823d8befd360fcd5ea01efdea6abf32c567" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 19,
   "ts": "2026-09-13T03:30:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "unit.output",
   "actor": "glm-5.3",
   "summary": "music.* strings machine-drafted into the corpus, all docked tongues, drafting pass recorded",
   "cost_usd": 0,
   "artifacts": [
    "surfaces/lang-corpus.json"
   ],
   "note": "⚙ machine drafts, no attestation claimed",
   "hash": "6f5533c62bcb2b5bd214554991c150a695bfdde07ed1e779a34c61401858d48b" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 20,
   "ts": "2026-09-13T03:50:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "verify.pass",
   "actor": "independent verification",
   "summary": "corpus integrity green — every key exists, every tongue covered, English matches the page",
   "cost_usd": 0,
   "artifacts": [
    "e2e/estate-source.mjs"
   ],
   "note": "",
   "hash": "a50f04f6af5dbdb7eaa959d105c8a4cfb662738d077f1b53b9664b3559817816" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 21,
   "ts": "2026-09-13T03:55:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "evaluator.continue",
   "actor": "milestone evaluator",
   "summary": "M2 verified — spend $41.76 of $70.00; release M3",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "fac05f0e0949470a28e66ba8e7d9434d2b2ec52ef50722ff9e3cd2de3b8010b1" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 22,
   "ts": "2026-09-13T03:56:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "treasury.release",
   "actor": "milestone evaluator",
   "summary": "milestone M3 released — final verification and report",
   "cost_usd": 17.28,
   "artifacts": [],
   "note": "testnet accounting",
   "hash": "3210a2239091689b7c8c8a67d9c438267ce7b318c456573ea090f1dcece6eb2e" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 23,
   "ts": "2026-09-13T04:20:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "verify.pass",
   "actor": "independent verification",
   "summary": "final walk green — projected figures compared against receipt sums",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "084239aac4dfaf462de06824377af4564e636758e123794ae39457f06d9f0010" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 24,
   "ts": "2026-09-13T04:25:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "evaluator.continue",
   "actor": "milestone evaluator",
   "summary": "M3 verified — all milestones delivered; mission closes",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "7e0fd9ddbb6d0d1ebd2109c50eaf9ab022efb2724fe061cfc0fe06368e4fb581" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 25,
   "ts": "2026-09-13T04:30:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "report.final",
   "actor": "bAiGent-01",
   "summary": "final outcome report filed — projected vs actual compared from receipts",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "3910642faf4f6f774bf9c0df36887930e8ea0f6273df82582e3df55ce2c84bee" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 26,
   "ts": "2026-09-13T04:31:00Z",
   "mission": "bnr-op-2026-001",
   "kind": "rep.update",
   "actor": "dao registrar",
   "summary": "team reputation updated from delivery, cost accuracy and truthful reporting",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "62bc08b147909ebd67ed7a2ff7265a79849b1d489be052c4af0543c4edafa718" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 27,
   "ts": "2026-09-13T06:10:00Z",
   "mission": "bnr-op-2026-002",
   "kind": "proposal.draft",
   "actor": "glm-5.3",
   "summary": "mission drafted — two cameras, one meter: the constraint is named in the objective",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "fc2e511c175b025464084b8820fb82f2d7b29d99bc0e3791a84b2ce467e28fae" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 28,
   "ts": "2026-09-13T06:24:00Z",
   "mission": "bnr-op-2026-002",
   "kind": "budget.calc",
   "actor": "gpt-6-astra",
   "summary": "budget worksheet computed — bandwidth-led estimate for the second inlet",
   "cost_usd": 0,
   "artifacts": [],
   "note": "calculator: mission-core.js budget()",
   "hash": "4837662626b53c0a97705b4db777e31a6d8243dd4f9a9f5bdc538c419aa6cb74" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 29,
   "ts": "2026-09-13T06:30:00Z",
   "mission": "bnr-op-2026-002",
   "kind": "review.submit",
   "actor": "bAiGent-01",
   "summary": "proposal submitted to independent review — awaiting ceiling",
   "cost_usd": 0,
   "artifacts": [],
   "note": "state: review",
   "hash": "dcf9918d0b2931d5c6de1e36e6ac1bdad7c02c6a7625275e9ce623fcad35450d" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 30,
   "ts": "2026-09-12T20:40:00Z",
   "mission": "bnr-op-2026-003",
   "kind": "proposal.draft",
   "actor": "fable",
   "summary": "mission drafted — fence readiness against the observed 0.18.1",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "525e465e44115162b88e522fdabf4094626d7a823cd377bcba394f3366e46cbb" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 31,
   "ts": "2026-09-12T20:52:00Z",
   "mission": "bnr-op-2026-003",
   "kind": "budget.calc",
   "actor": "glm-5.3",
   "summary": "budget worksheet computed — storage-led estimate for the fence loop file",
   "cost_usd": 0,
   "artifacts": [],
   "note": "calculator: mission-core.js budget()",
   "hash": "b0fa2e1afdbd75f77e5c8e5e95f6fb4cdfe907b4164e98350b028e7bf926ce4c" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 32,
   "ts": "2026-09-12T21:05:00Z",
   "mission": "bnr-op-2026-003",
   "kind": "review.verdict",
   "actor": "independent-review · astra",
   "summary": "bounded sweep approved — ceiling recommended",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "2ebd53f66979e324fb7855f2a94f69550a2b4db0a1d933ca901090b9404a4862" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 33,
   "ts": "2026-09-12T21:15:00Z",
   "mission": "bnr-op-2026-003",
   "kind": "ceiling.approve",
   "actor": "founder · LOViS",
   "summary": "spending ceiling approved at $19.00",
   "cost_usd": 0,
   "artifacts": [],
   "note": "human lever, logged like every other act",
   "hash": "7997d5611566ee10166f86d3f6f05e9af36ee3fcc97e5639278ad2f4c8a78604" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 34,
   "ts": "2026-09-12T21:20:00Z",
   "mission": "bnr-op-2026-003",
   "kind": "treasury.fund",
   "actor": "dao treasury",
   "summary": "milestone M1 funded — $6.01 against the ceiling",
   "cost_usd": 6.01,
   "artifacts": [],
   "note": "testnet accounting",
   "hash": "57943f863e456673f89e5d872948b57358e6ceab302bb794e1c3a785aecd4e8b" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 35,
   "ts": "2026-09-12T21:30:00Z",
   "mission": "bnr-op-2026-003",
   "kind": "unit.start",
   "actor": "glm-5.3",
   "summary": "work unit W1 started — version pin verification",
   "cost_usd": 0.96,
   "artifacts": [],
   "note": "8 runtime hours × $0.12",
   "hash": "33afbd8a60b266d794c2db91b15258373cf4097a9c61612bdf47730279183a50" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 36,
   "ts": "2026-09-13T00:15:00Z",
   "mission": "bnr-op-2026-003",
   "kind": "unit.output",
   "actor": "glm-5.3",
   "summary": "W1 delivered — pinned-version table with sources; M2 repro sketched",
   "cost_usd": 0,
   "artifacts": [],
   "note": "",
   "hash": "2576d02efb19a4f1249f985a1c09bed23c605eb86eb9f3614dfdc40dcac5671f" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 37,
   "ts": "2026-09-13T00:20:00Z",
   "mission": "bnr-op-2026-003",
   "kind": "gate.request",
   "actor": "glm-5.3",
   "summary": "W2 requested production access to deploy the fence config to the prod box",
   "cost_usd": 0,
   "artifacts": [],
   "note": "controls.production_access = false",
   "hash": "c887f767dcff4ebf57c70a4c6a7f242af3fe4f80f6f26879bab56592cc296b61" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 38,
   "ts": "2026-09-13T00:21:00Z",
   "mission": "bnr-op-2026-003",
   "kind": "evaluator.pause",
   "actor": "milestone evaluator",
   "summary": "room paused — production access is outside the approved envelope",
   "cost_usd": 0,
   "artifacts": [],
   "note": "the agents never deploy what the human has not unlocked",
   "hash": "808b3b038ecfafe8283c80942558d5de883dc104e6c728d21e3a0560a929e280" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  },
  {
   "seq": 39,
   "ts": "2026-09-13T00:22:00Z",
   "mission": "bnr-op-2026-003",
   "kind": "evaluator.escalate",
   "actor": "milestone evaluator",
   "summary": "escalated to the attending human — production_changes requires their word",
   "cost_usd": 0,
   "artifacts": [],
   "note": "awaiting founder decision",
   "hash": "3f2ab2a38b383e2ec86115e3f674611d0d419d62cd411ebdec5975fdceece092" // PUBLIC-CONSTANT: public receipt-chain hash (sha-256, not a secret)
  }
 ]
};
