// bsigner-nerve.test.mjs — the bSigner→SETTLE nerve, proven against the real
// organ. The kernel's `authorityHash` check ("the authority is not the one
// that was signed") has meaning only when something actually signs the
// authority; this suite is that something being real: an ML-DSA keyset
// generated by the organ itself, a bheart.signature/1 envelope over the
// domain-separated authority bytes, and the organ's own verification gating
// settle() before a single adapter verb runs.
//
// Needs the built organ: SETTLE_BSIGNER_BIN=target/debug/bsigner (the CI
// `test` job builds it). Without it the suite is SKIPPED by name, never
// passed — same law as solana-native.test.mjs.
import test from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { buildGenericInvoice } from "../../scripts/lib/bpay-invoice-generic.mjs";
import { AUTHORITY_DOMAIN, CONTRACT, VERBS, buildAuthority, buildIntent, descriptorHash, digest, settle } from "../../scripts/lib/bpay-settle.mjs";
import { authoritySigningBytes, signAuthority, verifyAuthoritySignature, settleSigned } from "./bsigner-authority.mjs";

const BIN = process.env.SETTLE_BSIGNER_BIN;
const skip = BIN ? false : "SETTLE_BSIGNER_BIN not set: build crates/bsigner first";

const NOW = "2026-10-06T12:00:00.000Z";
const NOT_AFTER = "2026-10-06T17:30:00.000Z";
const QUOTE_EXPIRES = "2026-10-06T18:00:00.000Z";
const ASSET = "FAKE";
const OWED = "20000";
const RECIPIENT = "fake:merchant-address";

// An honest fake of a shell-submits rail: every verb the kernel demands,
// no more cleverness than the contract requires. The nerve under test is the
// AUTHORITY signature; payload signing stays a stub by design (the rail
// vault's job — see bsigner-authority.mjs's header).
const DESC = {
  contract: CONTRACT, adapter_id: "fake-shell", network: "bnet:fake",
  submit_model: "shell-submits",
  assets: { [ASSET]: { decimals: 6, ref: "native" } },
  evidence_ceiling: "tx-hash",
  authority_models: ["bounded"],
  verbs: [...VERBS],
  privacy_satisfies: [],
};
function fakeAdapter() {
  const calls = [];
  const adapter = {
    async network() { return DESC; },
    async balance() { return { asset: ASSET, atto: "1000000" }; },
    async prepare(intent) { calls.push("prepare"); return { intent_id: intent.intent_digest, expires_at: QUOTE_EXPIRES, rail: "fake" }; },
    async payloads(prepared) { return { mode: "shell-submits", items: [Buffer.from(JSON.stringify(prepared), "utf8")], spend: { asset_atto: OWED, recipient: RECIPIENT, max_native_fee_atto: "0" } }; },
    async combine(prepared, sigs) { calls.push("combine"); return { signed: { prepared, sigs }, predicted_ref: "fake-ref-1" }; },
    async submit(signed) { calls.push("submit"); return { ref: "fake-ref-1", accepted_at: NOW }; },
    async status() { return { phase: "submitted", assertion: null }; },
    async reconcile() { calls.push("reconcile"); return { records: [], observation: { oracle: "fake://local-reader" } }; },
  };
  return { adapter, calls };
}
const memOutbox = () => { const m = new Map(); return { get: async (k) => m.get(k) || null, persist: async (k, v) => { if (m.has(k)) return false; m.set(k, v); return true; } }; };
const signer = { sign: async (items) => items.map((b) => b.toString("base64")) };

function rig({ recipient = RECIPIENT } = {}) {
  const inv = buildGenericInvoice({ jobId: "nerve-1", issuedAt: NOW,
    lines: [{ kind: "service", asset: ASSET, quotes: [{ quote_hash: "q-nerve-01", amount_atto: OWED }] }],
    authorization: { ceilings: { [ASSET]: OWED }, authorizedBy: "test", stopConditions: [] } });
  const { authority } = buildAuthority({ principal: "person:payer", asset: ASSET, max_asset_atto: OWED, max_native_fee_atto: "0", recipient,
    not_after: NOT_AFTER, nonce: "nonce-nerve-0001", invoice_digest: inv.identity.contentDigest, adapter_manifest_hash: descriptorHash(DESC) });
  const intent = buildIntent({ invoice: inv, asset: ASSET, descriptor: DESC, authority,
    quote: { commitment: inv.commitment.digest, expires_at: QUOTE_EXPIRES }, refund: { policy: "refund-to-source" }, now: NOW });
  return { inv, authority, intent };
}

// the organ's own keygen, in a private keydir — no pre-baked key material
let keydir, keyId, key2Id;
test("the organ generates the principal's keyset", { skip }, async () => {
  keydir = await mkdtemp(join(tmpdir(), "bsigner-nerve-"));
  for (const [out, alg] of [[(k) => (keyId = k), "ml-dsa-65"], [(k) => (key2Id = k), "ml-dsa-44"]]) {
    const r = spawnSync(BIN, ["keygen", "--alg", alg, "--keydir", keydir], { encoding: "utf8" });
    assert.equal(r.status, 0, r.stderr);
    const j = JSON.parse(r.stdout);
    assert.ok(!r.stdout.includes("seed"), "keygen output must never carry secret material");
    out(j.key_id);
  }
});

test("the organ signs and verifies the domain-separated authority bytes", { skip }, async () => {
  const { authority } = rig();
  const bytes = authoritySigningBytes(authority);
  assert.ok(bytes.subarray(0, AUTHORITY_DOMAIN.length).equals(Buffer.from(AUTHORITY_DOMAIN)), "the domain rides in the signed bytes");
  const { envelope, authority_hash } = await signAuthority({ authority, bin: BIN, keyId, keydir });
  assert.equal(envelope.type, "bheart.signature/1");
  assert.equal(envelope.alg, "ml-dsa-65");
  assert.equal(envelope.content.bytes, bytes.length);
  assert.equal(authority_hash, digest(AUTHORITY_DOMAIN, authority));
  assert.equal(await verifyAuthoritySignature({ authority, envelope, bin: BIN, keyId, keydir }), true);
});

test("settleSigned runs the kernel end to end under the signed authority", { skip }, async () => {
  const { inv, intent } = rig();
  const { envelope } = await signAuthority({ authority: intent.authority, bin: BIN, keyId, keydir });
  const { adapter, calls } = fakeAdapter();
  const run = await settleSigned({ adapter, intent, invoice: inv, envelope, bin: BIN, keyId, keydir, signer, outbox: memOutbox(), now: NOW, issuedAt: NOW });
  assert.deepEqual(calls, ["prepare", "combine", "submit", "reconcile"], "the full kernel path ran");
  assert.equal(run.receipt.phase, "submitted");
  assert.ok(run.receipt.receipt_digest.startsWith("sha256:"));
  assert.equal(run.authority_envelope, envelope, "the run carries the signature it settled under");
});

test("an authority edited after signing never reaches an adapter verb", { skip }, async () => {
  const good = rig();
  const { envelope } = await signAuthority({ authority: good.authority, bin: BIN, keyId, keydir });
  // the attacker's move: change where the money goes, keep the signature
  const edited = rig({ recipient: "fake:attacker-address" });
  assert.notEqual(edited.intent.authority_hash, good.intent.authority_hash);
  const { adapter, calls } = fakeAdapter();
  await assert.rejects(
    settleSigned({ adapter, intent: edited.intent, invoice: edited.inv, envelope, bin: BIN, keyId, keydir, signer, outbox: memOutbox(), now: NOW }),
    (e) => e.code === "SETTLE_AUTHORITY_SIG",
  );
  assert.deepEqual(calls, [], "refused before prepare — assert-rejection before requests");
});

test("another key's signature is not the principal's", { skip }, async () => {
  const { authority } = rig();
  const { envelope } = await signAuthority({ authority, bin: BIN, keyId: key2Id, keydir });
  await assert.rejects(
    verifyAuthoritySignature({ authority, envelope, bin: BIN, keyId, keydir }),
    (e) => e.code === "SETTLE_AUTHORITY_SIG",
  );
});

test("without the nerve, the kernel still refuses an authority hash that was not the signed one", { skip }, async () => {
  const a = rig();
  const b = rig({ recipient: "fake:someone-else" });
  const { adapter } = fakeAdapter();
  await assert.rejects(
    settle({ adapter, intent: a.intent, invoice: a.inv, signer, outbox: memOutbox(), now: NOW, authorityHash: b.intent.authority_hash }),
    /not the one that was signed/,
  );
});

test("keydir cleanup", { skip }, async () => {
  await rm(keydir, { recursive: true, force: true });
});
